  // ADDITIONAL PATTERNS TO REACH 200+ - Part 2
  {
    name: 'What I Learned From',
    category: 'storytelling',
    pattern: 'what I learned from {source}: {lesson_1}, {lesson_2}, {lesson_3}',
    description: 'Multiple lessons from single source',
    niches: ['business', 'fitness', 'lifestyle', 'travel', 'parenting'],
    postTypes: ['post'],
    avgEngagementRate: 9.3,
    successRate: 84,
    exampleCaptions: ['what I learned from failure: resilience, humility, persistence'],
    trending: true
  },
  {
    name: 'Not What You Think',
    category: 'hook',
    pattern: '{topic} is not what you think: {surprising_truth}',
    description: 'Challenges common assumptions',
    niches: ['fitness', 'business', 'food', 'lifestyle', 'beauty'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 9.6,
    successRate: 86,
    exampleCaptions: ['success is not what you think: it\'s consistency, not luck'],
    trending: true
  },
  {
    name: 'Year Ago Today',
    category: 'storytelling',
    pattern: 'year ago today: {past_state} → today: {present_state} → grateful for: {growth}',
    description: 'Annual reflection on growth',
    niches: ['fitness', 'business', 'lifestyle', 'travel'],
    postTypes: ['post'],
    avgEngagementRate: 10.2,
    successRate: 88,
    exampleCaptions: ['year ago today: unhappy corporate job → today: thriving entrepreneur'],
    trending: true
  },
  {
    name: 'Ways To',
    category: 'structure',
    pattern: '{number} ways to {achieve_goal}: {actionable_list}',
    description: 'Practical how-to list format',
    niches: ['fitness', 'business', 'food', 'lifestyle', 'beauty'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 8.9,
    successRate: 83,
    exampleCaptions: ['5 ways to make mornings easier: prep clothes, set alarms, early bedtime'],
    trending: true
  },
  {
    name: 'Overrated vs Underrated',
    category: 'structure',
    pattern: 'overrated: {popular_thing} → underrated: {overlooked_thing}',
    description: 'Contrasts hype with hidden gems',
    niches: ['travel', 'food', 'fitness', 'beauty', 'business'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 9.8,
    successRate: 87,
    exampleCaptions: ['overrated: abs → underrated: mental health and consistency'],
    trending: true
  },
  {
    name: 'Game Changer',
    category: 'hook',
    pattern: 'absolute game changer: {discovery} → why didn\'t I do this sooner?',
    description: 'Emphatic recommendation',
    niches: ['food', 'fitness', 'tech', 'business', 'lifestyle'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 9.4,
    successRate: 85,
    exampleCaptions: ['absolute game changer: meal planning on Sundays'],
    trending: true
  },
  {
    name: 'Reality Of',
    category: 'structure',
    pattern: 'the reality of {lifestyle/goal}: {honest_breakdown}',
    description: 'Transparent look at reality',
    niches: ['business', 'fitness', 'travel', 'parenting', 'lifestyle'],
    postTypes: ['post'],
    avgEngagementRate: 10.4,
    successRate: 89,
    exampleCaptions: ['the reality of entrepreneurship: unglamorous, lonely, uncertain, rewarding'],
    trending: true
  },
  {
    name: 'Started Doing This',
    category: 'hook',
    pattern: 'started doing this and {positive_outcome}: {specific_action}',
    description: 'Simple cause and effect',
    niches: ['fitness', 'lifestyle', 'business', 'food', 'beauty'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 9.1,
    successRate: 84,
    exampleCaptions: ['started doing this and everything changed: morning pages'],
    trending: true
  },
  {
    name: 'No Shame In',
    category: 'hook',
    pattern: 'no shame in: {list_of_acceptable_things}',
    description: 'Permission-giving format',
    niches: ['lifestyle', 'fitness', 'parenting', 'business', 'food'],
    postTypes: ['post'],
    avgEngagementRate: 9.5,
    successRate: 86,
    exampleCaptions: ['no shame in: takeout, rest days, asking for help, changing your mind'],
    trending: true
  },
  {
    name: 'Best Investment',
    category: 'structure',
    pattern: 'best investment I made: {thing} → cost: {amount} → value: priceless',
    description: 'Value-focused recommendation',
    niches: ['business', 'fitness', 'lifestyle', 'beauty', 'tech'],
    postTypes: ['post'],
    avgEngagementRate: 9.3,
    successRate: 84,
    exampleCaptions: ['best investment I made: therapy → cost: $150/session → value: priceless'],
    trending: true
  },
  {
    name: 'Lessons In',
    category: 'storytelling',
    pattern: '{time_period} of {activity}: lessons in {theme_1}, {theme_2}, {theme_3}',
    description: 'Time-based learning summary',
    niches: ['business', 'fitness', 'travel', 'lifestyle', 'parenting'],
    postTypes: ['post'],
    avgEngagementRate: 9.7,
    successRate: 86,
    exampleCaptions: ['5 years of entrepreneurship: lessons in patience, resilience, self-belief'],
    trending: true
  },
  {
    name: 'Quick Win',
    category: 'structure',
    pattern: 'quick win: {easy_action} → {immediate_benefit}',
    description: 'Low-effort high-return actions',
    niches: ['fitness', 'business', 'food', 'lifestyle', 'tech'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 8.8,
    successRate: 82,
    exampleCaptions: ['quick win: drink water first thing → instant energy boost'],
    trending: true
  },
  {
    name: 'Monthly Reset',
    category: 'structure',
    pattern: 'monthly reset: {routine} → keeps me {benefit}',
    description: 'Regular refresh ritual',
    niches: ['lifestyle', 'business', 'fitness', 'beauty'],
    postTypes: ['post'],
    avgEngagementRate: 9.0,
    successRate: 83,
    exampleCaptions: ['monthly reset: digital detox weekend → keeps me sane'],
    trending: true
  },
  {
    name: 'Stopped Waiting For',
    category: 'hook',
    pattern: 'stopped waiting for {condition} → started {action} → {outcome}',
    description: 'Empowerment through action',
    niches: ['business', 'fitness', 'lifestyle', 'travel'],
    postTypes: ['post'],
    avgEngagementRate: 9.9,
    successRate: 87,
    exampleCaptions: ['stopped waiting for perfect time → started anyway → best decision ever'],
    trending: true
  },
  {
    name: 'Accountability Post',
    category: 'engagement',
    pattern: 'my goal this {timeframe}: {goal} → hold me accountable',
    description: 'Public commitment for accountability',
    niches: ['fitness', 'business', 'lifestyle', 'food'],
    postTypes: ['post'],
    avgEngagementRate: 9.2,
    successRate: 84,
    exampleCaptions: ['my goal this month: workout 4x/week → hold me accountable'],
    trending: true
  },
  {
    name: 'Wish I Started',
    category: 'hook',
    pattern: 'wish I started {activity} sooner: {benefit_1}, {benefit_2}, {benefit_3}',
    description: 'Regret-tinged recommendation',
    niches: ['fitness', 'business', 'lifestyle', 'food', 'travel'],
    postTypes: ['post'],
    avgEngagementRate: 9.4,
    successRate: 85,
    exampleCaptions: ['wish I started strength training sooner: confidence, energy, mental clarity'],
    trending: true
  },
  {
    name: 'The Cost Of',
    category: 'structure',
    pattern: 'the cost of {choice}: not money, but {real_cost}',
    description: 'Non-monetary cost analysis',
    niches: ['business', 'lifestyle', 'fitness', 'parenting'],
    postTypes: ['post'],
    avgEngagementRate: 10.1,
    successRate: 88,
    exampleCaptions: ['the cost of saying yes to everything: not money, but your peace of mind'],
    trending: true
  },
  {
    name: 'Simplified My',
    category: 'structure',
    pattern: 'simplified my {area}: before {complex} → now {simple} → {benefit}',
    description: 'Minimalist approach benefits',
    niches: ['lifestyle', 'fashion', 'food', 'beauty', 'business'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 9.3,
    successRate: 84,
    exampleCaptions: ['simplified my wardrobe: 100 items → 30 items → less stress, better style'],
    trending: true
  },
  {
    name: 'Wake Up Call',
    category: 'storytelling',
    pattern: '{wake_up_moment} → realized: {truth} → changed: {action}',
    description: 'Pivotal realization story',
    niches: ['fitness', 'business', 'lifestyle', 'food'],
    postTypes: ['post'],
    avgEngagementRate: 10.5,
    successRate: 89,
    exampleCaptions: ['burnout → realized: hustle culture is toxic → changed: set boundaries'],
    trending: true
  },
  {
    name: 'Stopped Feeling Guilty About',
    category: 'hook',
    pattern: 'stopped feeling guilty about: {list} → game changer',
    description: 'Guilt-release permission',
    niches: ['lifestyle', 'fitness', 'parenting', 'food'],
    postTypes: ['post'],
    avgEngagementRate: 9.8,
    successRate: 87,
    exampleCaptions: ['stopped feeling guilty about: rest, saying no, taking time for myself'],
    trending: true
  },
  {
    name: 'Weekly Review',
    category: 'engagement',
    pattern: 'this week: wins {list} → lessons {list} → next week: {goals}',
    description: 'Structured weekly reflection',
    niches: ['business', 'fitness', 'lifestyle', 'parenting'],
    postTypes: ['post'],
    avgEngagementRate: 8.9,
    successRate: 82,
    exampleCaptions: ['this week: 3 workouts, new client → lessons: consistency matters'],
    trending: true
  },
  {
    name: 'Minimalist Approach',
    category: 'structure',
    pattern: 'you only need {minimal_list} → forget {excess_list}',
    description: 'Essential-only philosophy',
    niches: ['fitness', 'food', 'beauty', 'fashion', 'business'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 9.2,
    successRate: 84,
    exampleCaptions: ['you only need: barbell, plates, bench → forget fancy machines'],
    trending: true
  },
  {
    name: 'Progress Not Perfection',
    category: 'hook',
    pattern: 'progress not perfection: {imperfect_action} beats {perfect_inaction}',
    description: 'Anti-perfectionism message',
    niches: ['fitness', 'business', 'lifestyle', 'food'],
    postTypes: ['post'],
    avgEngagementRate: 9.4,
    successRate: 85,
    exampleCaptions: ['progress not perfection: messy meal prep beats ordering takeout'],
    trending: true
  },
  {
    name: 'Small Changes Big Impact',
    category: 'structure',
    pattern: 'small change: {action} → big impact: {result}',
    description: 'Compounding benefits message',
    niches: ['fitness', 'lifestyle', 'business', 'food', 'beauty'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 9.1,
    successRate: 83,
    exampleCaptions: ['small change: 10 min walk daily → big impact: improved mood and energy'],
    trending: true
  },
  {
    name: 'Energy Audit',
    category: 'structure',
    pattern: 'what drains my energy: {list} → what fills it: {list}',
    description: 'Energy management framework',
    niches: ['lifestyle', 'business', 'parenting', 'fitness'],
    postTypes: ['post'],
    avgEngagementRate: 9.6,
    successRate: 86,
    exampleCaptions: ['drains: social media, people-pleasing → fills: nature, movement, solitude'],
    trending: true
  },
  {
    name: 'Build In Public',
    category: 'engagement',
    pattern: 'building {project} in public: {update} → questions?',
    description: 'Transparent progress sharing',
    niches: ['business', 'fitness', 'lifestyle'],
    postTypes: ['post'],
    avgEngagementRate: 9.3,
    successRate: 84,
    exampleCaptions: ['building my business in public: month 3, $2k revenue → questions?'],
    trending: true
  },
  {
    name: 'Daily Non-Negotiable',
    category: 'structure',
    pattern: 'my daily non-negotiable: {habit} → skipped it once, never again',
    description: 'Critical habit identification',
    niches: ['fitness', 'lifestyle', 'business', 'beauty'],
    postTypes: ['post'],
    avgEngagementRate: 9.0,
    successRate: 83,
    exampleCaptions: ['my daily non-negotiable: morning walk → skipped it once, felt terrible'],
    trending: true
  },
  {
    name: 'Worth The Hype',
    category: 'structure',
    pattern: '{popular_thing}: worth the hype? → {honest_verdict} → {reasoning}',
    description: 'Trend evaluation',
    niches: ['beauty', 'food', 'fitness', 'tech', 'fashion'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 9.7,
    successRate: 86,
    exampleCaptions: ['air fryer: worth the hype? → absolutely → convenience and versatility'],
    trending: true
  },
  {
    name: 'Made It Myself',
    category: 'hook',
    pattern: 'made this myself: {creation} → cost: ${amount} → store price: ${comparison}',
    description: 'DIY savings showcase',
    niches: ['food', 'fashion', 'lifestyle', 'beauty'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 9.4,
    successRate: 85,
    exampleCaptions: ['made this myself: cold brew → cost: $2 → coffee shop: $6'],
    trending: true
  },
  {
    name: 'Comparison Trap',
    category: 'storytelling',
    pattern: 'compared myself to {others} → felt {negative} → remembered: {truth}',
    description: 'Overcoming comparison',
    niches: ['lifestyle', 'fitness', 'business', 'parenting'],
    postTypes: ['post'],
    avgEngagementRate: 10.3,
    successRate: 88,
    exampleCaptions: ['compared myself to others → felt inadequate → remembered: my pace is perfect'],
    trending: true
  },
  {
    name: 'Sunday Reset Ritual',
    category: 'structure',
    pattern: 'Sunday reset: {ritual_steps} → sets up entire week',
    description: 'Weekly preparation routine',
    niches: ['lifestyle', 'food', 'business', 'fitness'],
    postTypes: ['post'],
    avgEngagementRate: 9.1,
    successRate: 83,
    exampleCaptions: ['Sunday reset: meal prep, plan workouts, review goals → sets up entire week'],
    trending: true
  },
  {
    name: 'Boundary Setting',
    category: 'hook',
    pattern: 'setting this boundary changed everything: {boundary} → {impact}',
    description: 'Boundary success story',
    niches: ['business', 'lifestyle', 'parenting', 'fitness'],
    postTypes: ['post'],
    avgEngagementRate: 10.2,
    successRate: 88,
    exampleCaptions: ['setting this boundary: no work after 6pm → got my life back'],
    trending: true
  },
  {
    name: 'Morning vs Evening',
    category: 'engagement',
    pattern: 'morning people vs evening people: {comparison} → which are you?',
    description: 'Chronotype identification',
    niches: ['lifestyle', 'fitness', 'business'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 9.3,
    successRate: 84,
    exampleCaptions: ['morning workout vs evening workout → which are you?'],
    trending: true
  },
  {
    name: 'Budget Breakdown',
    category: 'structure',
    pattern: '{experience} on ${budget}: {itemized_spending} → totally doable',
    description: 'Budget-conscious planning',
    niches: ['travel', 'food', 'lifestyle', 'fashion'],
    postTypes: ['post'],
    avgEngagementRate: 9.8,
    successRate: 87,
    exampleCaptions: ['Paris on $50/day: hostel $20, food $20, attractions $10 → totally doable'],
    trending: true
  },
  {
    name: 'Learning Curve',
    category: 'storytelling',
    pattern: 'week 1: {struggle} → month 1: {progress} → now: {mastery}',
    description: 'Skill acquisition journey',
    niches: ['fitness', 'business', 'food', 'photography', 'tech'],
    postTypes: ['post'],
    avgEngagementRate: 9.5,
    successRate: 85,
    exampleCaptions: ['week 1: couldn\'t do pushup → month 1: 10 pushups → now: 50 pushups'],
    trending: true
  },
  {
    name: 'Permission To',
    category: 'hook',
    pattern: 'permission to {action} granted → no explanation needed',
    description: 'Empowerment statement',
    niches: ['lifestyle', 'fitness', 'parenting', 'business'],
    postTypes: ['post'],
    avgEngagementRate: 9.4,
    successRate: 85,
    exampleCaptions: ['permission to rest granted → no explanation needed'],
    trending: true
  },
  {
    name: 'The Switch',
    category: 'structure',
    pattern: 'switched from {old_habit} to {new_habit}: {benefits}',
    description: 'Habit swap success',
    niches: ['fitness', 'lifestyle', 'food', 'business', 'beauty'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 9.2,
    successRate: 84,
    exampleCaptions: ['switched from coffee to matcha: sustained energy, no crash'],
    trending: true
  },
  {
    name: 'Unpopular Truth',
    category: 'hook',
    pattern: 'unpopular truth: {harsh_reality} → but it needed to be said',
    description: 'Difficult honesty',
    niches: ['fitness', 'business', 'lifestyle', 'food'],
    postTypes: ['post', 'reel'],
    avgEngagementRate: 10.4,
    successRate: 89,
    exampleCaptions: ['unpopular truth: no one is coming to save you → but it needed to be said'],
    trending: true
  },
  {
    name: 'Monthly Favorites',
    category: 'structure',
    pattern: '{month} favorites: {category_1} {item}, {category_2} {item}, {category_3} {item}',
    description: 'Curated recommendations',
    niches: ['beauty', 'food', 'lifestyle', 'fashion', 'tech'],
    postTypes: ['post'],
    avgEngagementRate: 8.9,
    successRate: 82,
    exampleCaptions: ['June favorites: skincare: vitamin C, food: overnight oats, podcast: Huberman'],
    trending: true
  },
  {
    name: 'Golden Rule',
    category: 'structure',
    pattern: 'my golden rule for {area}: {principle} → changed everything',
    description: 'Core guiding principle',
    niches: ['fitness', 'business', 'lifestyle', 'food', 'parenting'],
    postTypes: ['post'],
    avgEngagementRate: 9.6,
    successRate: 86,
    exampleCaptions: ['my golden rule for nutrition: eat foods you actually enjoy → changed everything'],
    trending: true
  },
