/**
 * The version-controlled Baseline_Benchmark request set
 * (spec: veegpt-context-optimization, Req 2.1, 2.2).
 *
 * Contains ≥3 distinct requests for EACH of the 15 required categories. This
 * file is the single source of truth for what VeeGPT is benchmarked against;
 * changing a request here changes the baseline, so it is intentionally explicit
 * and reviewed as code.
 *
 * Tool names referenced in `expectedTools` match the real definitions in
 * `server/routes/veegpt-tools.ts`.
 */

import type { BenchmarkRequest } from './types';

export const BASELINE_REQUEST_SET: BenchmarkRequest[] = [
  // ── simple-chat ──────────────────────────────────────────────────────────
  {
    id: 'simple-chat-1',
    category: 'simple-chat',
    description: 'Plain greeting, no tools, no memory.',
    priorMessages: [],
    message: 'Hey VeeGPT, how are you today?',
    expectedTools: [],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'simple-chat-2',
    category: 'simple-chat',
    description: 'General conceptual question answerable without any tool.',
    priorMessages: [],
    message: 'What makes a good Instagram Reel hook in one sentence?',
    expectedTools: [],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'simple-chat-3',
    category: 'simple-chat',
    description: 'Small-talk thanks that should not trigger any capability.',
    priorMessages: [{ role: 'assistant', content: 'Here is your caption draft.' }],
    message: 'Thanks, that is helpful!',
    expectedTools: [],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },

  // ── follow-up ────────────────────────────────────────────────────────────
  {
    id: 'follow-up-1',
    category: 'follow-up',
    description: 'Refers to a caption produced in the prior turn.',
    priorMessages: [
      { role: 'user', content: 'Write a caption for my new coffee shop reel.' },
      { role: 'assistant', content: 'Draft caption: "Mornings taste better here ☕ #CoffeeReels"' },
    ],
    message: 'Make it shorter and punchier.',
    expectedTools: ['generate_caption'],
    expectedMemoryItems: [],
    expectedContextItems: ['coffee shop', 'caption'],
  },
  {
    id: 'follow-up-2',
    category: 'follow-up',
    description: 'References an earlier analytics answer.',
    priorMessages: [
      { role: 'user', content: 'How did my last post perform?' },
      { role: 'assistant', content: 'Your last post reached 4,200 accounts with a 6% engagement rate.' },
    ],
    message: 'Why was the engagement rate that high?',
    expectedTools: ['get_analytics_insight'],
    expectedMemoryItems: [],
    expectedContextItems: ['engagement rate', '6%'],
  },
  {
    id: 'follow-up-3',
    category: 'follow-up',
    description: 'Pronoun reference ("that one") to a previously listed option.',
    priorMessages: [
      { role: 'user', content: 'Give me three reel ideas for a bakery.' },
      { role: 'assistant', content: '1) Behind-the-scenes dough making 2) Customer taste test 3) 60-second croissant recipe' },
    ],
    message: 'Expand that second one into a full script.',
    expectedTools: [],
    expectedMemoryItems: [],
    expectedContextItems: ['taste test', 'bakery'],
  },

  // ── content-creation ─────────────────────────────────────────────────────
  {
    id: 'content-creation-1',
    category: 'content-creation',
    description: 'Explicit caption generation request.',
    priorMessages: [],
    message: 'Write me 3 caption options for a fitness transformation reel.',
    expectedTools: ['generate_caption'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'content-creation-2',
    category: 'content-creation',
    description: 'Explicit hashtag generation request.',
    priorMessages: [],
    message: 'Give me hashtags for a travel post about Bali.',
    expectedTools: ['generate_hashtags'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'content-creation-3',
    category: 'content-creation',
    description: 'Caption + hashtags in one content request.',
    priorMessages: [],
    message: 'Draft a caption and hashtags for my new skincare product launch.',
    expectedTools: ['generate_caption', 'generate_hashtags'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },

  // ── analytics ────────────────────────────────────────────────────────────
  {
    id: 'analytics-1',
    category: 'analytics',
    description: 'Direct performance-insight request.',
    priorMessages: [],
    message: 'How is my Instagram account performing this month?',
    expectedTools: ['get_analytics_insight'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'analytics-2',
    category: 'analytics',
    description: 'Best-posting-time analytics request.',
    priorMessages: [],
    message: 'When is the best time for me to post to get the most engagement?',
    expectedTools: ['get_best_posting_time'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'analytics-3',
    category: 'analytics',
    description: 'Selected-account detailed analytics request.',
    priorMessages: [],
    message: 'Show me the detailed analytics for my selected account.',
    expectedTools: ['get_account_details'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },

  // ── social-listening ─────────────────────────────────────────────────────
  {
    id: 'social-listening-1',
    category: 'social-listening',
    description: 'Trend research in a niche.',
    priorMessages: [],
    message: 'What is trending in fitness content on Instagram right now?',
    expectedTools: ['research_trends'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'social-listening-2',
    category: 'social-listening',
    description: 'Web search for current sentiment.',
    priorMessages: [],
    message: 'What are people saying about the latest Instagram algorithm update?',
    expectedTools: ['search_web'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'social-listening-3',
    category: 'social-listening',
    description: 'Deep multi-source research report.',
    priorMessages: [],
    message: 'Create a deep research report on social media trends in sustainable fashion.',
    expectedTools: ['deep_research'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },

  // ── scheduling ───────────────────────────────────────────────────────────
  {
    id: 'scheduling-1',
    category: 'scheduling',
    description: 'Schedule a new post.',
    priorMessages: [],
    message: 'Schedule this reel to publish tomorrow at 6pm.',
    expectedTools: ['schedule_post'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'scheduling-2',
    category: 'scheduling',
    description: 'Reschedule an existing scheduled post.',
    priorMessages: [
      { role: 'user', content: 'Schedule my recipe post for Friday 9am.' },
      { role: 'assistant', content: 'Scheduled your recipe post for Friday at 9:00am.' },
    ],
    message: 'Actually move that to Saturday morning instead.',
    expectedTools: ['reschedule_post'],
    expectedMemoryItems: [],
    expectedContextItems: ['recipe post'],
  },
  {
    id: 'scheduling-3',
    category: 'scheduling',
    description: 'Cancel a scheduled post.',
    priorMessages: [],
    message: 'Cancel the post I have scheduled for this weekend.',
    expectedTools: ['cancel_scheduled_post'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },

  // ── automation ───────────────────────────────────────────────────────────
  {
    id: 'automation-1',
    category: 'automation',
    description: 'Duplicate a post as a recurring draft.',
    priorMessages: [],
    message: 'Duplicate my best performing post as a new draft I can reuse weekly.',
    expectedTools: ['duplicate_post'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'automation-2',
    category: 'automation',
    description: 'Bulk caption update across drafts.',
    priorMessages: [],
    message: 'Update the caption on my draft post to include our new promo code SAVE20.',
    expectedTools: ['update_post_caption'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'automation-3',
    category: 'automation',
    description: 'Schedule + generate content as an automated workflow.',
    priorMessages: [],
    message: 'Generate a caption for my weekly tips reel and schedule it for every Monday at 8am.',
    expectedTools: ['generate_caption', 'schedule_post'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },

  // ── multi-tool ───────────────────────────────────────────────────────────
  {
    id: 'multi-tool-1',
    category: 'multi-tool',
    description: 'Analytics + best time + content in one request.',
    priorMessages: [],
    message: 'Check how my account is doing, tell me the best time to post, and draft a caption for my next reel.',
    expectedTools: ['get_analytics_insight', 'get_best_posting_time', 'generate_caption'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'multi-tool-2',
    category: 'multi-tool',
    description: 'Research + caption + hashtags compound request.',
    priorMessages: [],
    message: 'Find what is trending in vegan recipes, then write a caption and hashtags based on it.',
    expectedTools: ['research_trends', 'generate_caption', 'generate_hashtags'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'multi-tool-3',
    category: 'multi-tool',
    description: 'Workspace data + schedule compound request.',
    priorMessages: [],
    message: 'Look up my most recent draft and schedule it for the best time tomorrow.',
    expectedTools: ['get_workspace_data', 'get_best_posting_time', 'schedule_post'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },

  // ── memory-dependent ─────────────────────────────────────────────────────
  {
    id: 'memory-dependent-1',
    category: 'memory-dependent',
    description: 'Recall a stored brand voice preference.',
    priorMessages: [],
    message: 'Write a caption in my usual brand voice for a product teaser.',
    expectedTools: ['generate_caption'],
    expectedMemoryItems: ['brand voice is witty and casual'],
    expectedContextItems: [],
  },
  {
    id: 'memory-dependent-2',
    category: 'memory-dependent',
    description: 'Save a durable preference to memory.',
    priorMessages: [],
    message: 'Remember that my target audience is women aged 25 to 34 interested in wellness.',
    expectedTools: ['remember_fact'],
    expectedMemoryItems: ['target audience is women aged 25 to 34'],
    expectedContextItems: [],
  },
  {
    id: 'memory-dependent-3',
    category: 'memory-dependent',
    description: 'Recall a stored niche when generating hashtags.',
    priorMessages: [],
    message: 'Give me hashtags that fit my niche.',
    expectedTools: ['generate_hashtags'],
    expectedMemoryItems: ['niche is home fitness'],
    expectedContextItems: [],
  },

  // ── long-conversation ────────────────────────────────────────────────────
  {
    id: 'long-conversation-1',
    category: 'long-conversation',
    description: 'Long thread; must retain the campaign objective set early.',
    priorMessages: [
      { role: 'user', content: 'I am launching a 6-week fitness challenge campaign.' },
      { role: 'assistant', content: 'Great, a 6-week fitness challenge. What is the goal?' },
      { role: 'user', content: 'The goal is 500 new signups.' },
      { role: 'assistant', content: 'Understood — 500 signups over 6 weeks.' },
      { role: 'user', content: 'Our brand color is teal and the tone is motivational.' },
      { role: 'assistant', content: 'Noted: teal branding, motivational tone.' },
      { role: 'user', content: 'We post on Instagram and TikTok.' },
      { role: 'assistant', content: 'Got it, Instagram and TikTok.' },
    ],
    message: 'Draft the launch caption for week one.',
    expectedTools: ['generate_caption'],
    expectedMemoryItems: [],
    expectedContextItems: ['fitness challenge', 'motivational', '500 signups'],
  },
  {
    id: 'long-conversation-2',
    category: 'long-conversation',
    description: 'Long thread; must retain content constraints agreed earlier.',
    priorMessages: [
      { role: 'user', content: 'Help me plan a product launch for our eco water bottle.' },
      { role: 'assistant', content: 'Sure — tell me the constraints.' },
      { role: 'user', content: 'No emojis, and keep captions under 100 characters.' },
      { role: 'assistant', content: 'Understood: no emojis, under 100 characters.' },
      { role: 'user', content: 'Audience is outdoor enthusiasts.' },
      { role: 'assistant', content: 'Noted: outdoor enthusiasts.' },
      { role: 'user', content: 'We want to emphasize sustainability.' },
      { role: 'assistant', content: 'Got it — sustainability focus.' },
    ],
    message: 'Now write the announcement caption.',
    expectedTools: ['generate_caption'],
    expectedMemoryItems: [],
    expectedContextItems: ['no emojis', 'sustainability', 'under 100 characters'],
  },
  {
    id: 'long-conversation-3',
    category: 'long-conversation',
    description: 'Long thread; must retain a decision made mid-conversation.',
    priorMessages: [
      { role: 'user', content: 'I need a content plan for my coaching business.' },
      { role: 'assistant', content: 'Happy to help. What formats do you prefer?' },
      { role: 'user', content: 'Mostly carousels and one reel per week.' },
      { role: 'assistant', content: 'Carousels plus one weekly reel — noted.' },
      { role: 'user', content: 'We decided to focus on LinkedIn first.' },
      { role: 'assistant', content: 'Decision recorded: LinkedIn first.' },
      { role: 'user', content: 'Posting three times a week.' },
      { role: 'assistant', content: 'Three posts per week.' },
    ],
    message: 'Summarize our agreed plan and draft Monday\'s post.',
    expectedTools: ['generate_caption'],
    expectedMemoryItems: [],
    expectedContextItems: ['LinkedIn first', 'carousels', 'three times a week'],
  },

  // ── ambiguous ────────────────────────────────────────────────────────────
  {
    id: 'ambiguous-1',
    category: 'ambiguous',
    description: 'Under-specified request that could mean several capabilities.',
    priorMessages: [],
    message: 'Can you help me with my post?',
    expectedTools: [],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'ambiguous-2',
    category: 'ambiguous',
    description: 'Vague "make it better" without a referenced artifact.',
    priorMessages: [],
    message: 'Make it better.',
    expectedTools: [],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'ambiguous-3',
    category: 'ambiguous',
    description: 'Ambiguous "grow" request spanning analytics/content/strategy.',
    priorMessages: [],
    message: 'How do I grow?',
    expectedTools: [],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },

  // ── persona-dependent ────────────────────────────────────────────────────
  {
    id: 'persona-dependent-1',
    category: 'persona-dependent',
    description: 'Strategist persona shapes a strategy answer.',
    priorMessages: [],
    message: 'Give me a 30-day growth strategy for my brand.',
    persona: 'strategist',
    tier: 'advanced',
    expectedTools: [],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'persona-dependent-2',
    category: 'persona-dependent',
    description: 'Creator persona shapes a creative answer.',
    priorMessages: [],
    message: 'Brainstorm 5 bold reel concepts for my streetwear brand.',
    persona: 'creator',
    tier: 'advanced',
    expectedTools: [],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'persona-dependent-3',
    category: 'persona-dependent',
    description: 'Analyst persona shapes a data-driven answer.',
    priorMessages: [],
    message: 'Interpret my engagement trend and tell me what to change.',
    persona: 'analyst',
    tier: 'advanced',
    expectedTools: ['get_analytics_insight'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },

  // ── tool-failure ─────────────────────────────────────────────────────────
  {
    id: 'tool-failure-1',
    category: 'tool-failure',
    description: 'Analytics tool fails; graceful degradation expected.',
    priorMessages: [],
    message: 'Show me my account analytics.',
    simulateToolFailure: true,
    expectedTools: ['get_analytics_insight'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'tool-failure-2',
    category: 'tool-failure',
    description: 'Scheduling tool fails; user is told and offered retry.',
    priorMessages: [],
    message: 'Schedule my post for tomorrow at noon.',
    simulateToolFailure: true,
    expectedTools: ['schedule_post'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'tool-failure-3',
    category: 'tool-failure',
    description: 'Web search fails; model still responds helpfully.',
    priorMessages: [],
    message: 'Search the web for the latest Reels best practices.',
    simulateToolFailure: true,
    expectedTools: ['search_web'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },

  // ── provider-fallback ────────────────────────────────────────────────────
  {
    id: 'provider-fallback-1',
    category: 'provider-fallback',
    description: 'Primary provider unavailable; fallback path handles request.',
    priorMessages: [],
    message: 'Write a short motivational caption for a Monday post.',
    simulateProviderFallback: true,
    expectedTools: ['generate_caption'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'provider-fallback-2',
    category: 'provider-fallback',
    description: 'Fallback while handling an analytics request.',
    priorMessages: [],
    message: 'How did my stories do this week?',
    simulateProviderFallback: true,
    expectedTools: ['get_analytics_insight'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'provider-fallback-3',
    category: 'provider-fallback',
    description: 'Fallback on a plain chat request (no tools).',
    priorMessages: [],
    message: 'Explain the difference between reach and impressions.',
    simulateProviderFallback: true,
    expectedTools: [],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },

  // ── complex-reasoning ────────────────────────────────────────────────────
  {
    id: 'complex-reasoning-1',
    category: 'complex-reasoning',
    description: 'Multi-step reasoning combining data and strategy.',
    priorMessages: [],
    message:
      'Given that my reach dropped 20% but saves went up, what does that mean and what 3 changes should I make?',
    expectedTools: ['get_analytics_insight'],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'complex-reasoning-2',
    category: 'complex-reasoning',
    description: 'Trade-off reasoning across posting frequency and quality.',
    priorMessages: [],
    message:
      'Should I post daily lower-effort content or 3x weekly high-effort content to grow fastest? Reason it through.',
    expectedTools: [],
    expectedMemoryItems: [],
    expectedContextItems: [],
  },
  {
    id: 'complex-reasoning-3',
    category: 'complex-reasoning',
    description: 'Plan synthesis from research + analytics + constraints.',
    priorMessages: [
      { role: 'user', content: 'My budget is $200/month and I can film twice a week.' },
      { role: 'assistant', content: 'Noted: $200/month, filming twice weekly.' },
    ],
    message:
      'Research what is working in my niche, look at my analytics, and build a realistic 4-week plan within my constraints.',
    expectedTools: ['research_trends', 'get_analytics_insight'],
    expectedMemoryItems: [],
    expectedContextItems: ['$200', 'twice a week'],
  },
];
