import mongoose from "mongoose";
import { IStorage } from "./storage";
import { User, Workspace, SocialAccount, Content, Analytics, AutomationRule, Suggestion, CreditTransaction, Referral, Subscription, Payment, Addon, WorkspaceMember, TeamInvitation, ContentRecommendation, UserContentHistory, Admin, CreativeBrief, ContentRepurpose, CompetitorAnalysis, InsertUser, InsertWorkspace, InsertSocialAccount, InsertContent, InsertAutomationRule, InsertAnalytics, InsertSuggestion, InsertCreditTransaction, InsertReferral, InsertSubscription, InsertPayment, InsertAddon, InsertWorkspaceMember, InsertTeamInvitation, InsertContentRecommendation, InsertUserContentHistory, InsertAdmin, InsertCreativeBrief, InsertContentRepurpose, InsertCompetitorAnalysis, WaitlistUser, InsertWaitlistUser } from "@shared/schema";
declare const UserModel: mongoose.Model<{
    status: string;
    username: string;
    email: string;
    credits: number;
    plan: string;
    totalReferrals: number;
    totalEarned: number;
    isOnboarded: boolean;
    hasUsedWaitlistBonus: boolean;
    dailyLoginStreak: number;
    isEmailVerified: boolean;
    onboardingStep: number;
    onboardingData: any;
    preferences: any;
    goals: any;
    socialPlatforms: any;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    tokenStatus: "active" | "expired" | "rate_limited" | "invalid";
    apiCallCount: number;
    firebaseUid?: string | null;
    displayName?: string | null;
    avatar?: string | null;
    stripeCustomerId?: string | null;
    stripeSubscriptionId?: string | null;
    referralCode?: string | null;
    referredBy?: string | null;
    trialExpiresAt?: NativeDate | null;
    discountCode?: string | null;
    discountExpiresAt?: NativeDate | null;
    lastLoginAt?: NativeDate | null;
    feedbackSubmittedAt?: NativeDate | null;
    emailVerificationCode?: string | null;
    emailVerificationExpiry?: NativeDate | null;
    niche?: string | null;
    targetAudience?: string | null;
    contentStyle?: string | null;
    postingFrequency?: string | null;
    businessType?: string | null;
    experienceLevel?: string | null;
    primaryObjective?: string | null;
    workspaceId?: string | null;
    onboardingCompletedAt?: NativeDate | null;
    instagramToken?: string | null;
    instagramRefreshToken?: string | null;
    instagramTokenExpiry?: NativeDate | null;
    instagramAccountId?: string | null;
    instagramUsername?: string | null;
    lastApiCallTimestamp?: NativeDate | null;
    rateLimitResetAt?: NativeDate | null;
}, {}, {}, {}, mongoose.Document<unknown, {}, {
    status: string;
    username: string;
    email: string;
    credits: number;
    plan: string;
    totalReferrals: number;
    totalEarned: number;
    isOnboarded: boolean;
    hasUsedWaitlistBonus: boolean;
    dailyLoginStreak: number;
    isEmailVerified: boolean;
    onboardingStep: number;
    onboardingData: any;
    preferences: any;
    goals: any;
    socialPlatforms: any;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    tokenStatus: "active" | "expired" | "rate_limited" | "invalid";
    apiCallCount: number;
    firebaseUid?: string | null;
    displayName?: string | null;
    avatar?: string | null;
    stripeCustomerId?: string | null;
    stripeSubscriptionId?: string | null;
    referralCode?: string | null;
    referredBy?: string | null;
    trialExpiresAt?: NativeDate | null;
    discountCode?: string | null;
    discountExpiresAt?: NativeDate | null;
    lastLoginAt?: NativeDate | null;
    feedbackSubmittedAt?: NativeDate | null;
    emailVerificationCode?: string | null;
    emailVerificationExpiry?: NativeDate | null;
    niche?: string | null;
    targetAudience?: string | null;
    contentStyle?: string | null;
    postingFrequency?: string | null;
    businessType?: string | null;
    experienceLevel?: string | null;
    primaryObjective?: string | null;
    workspaceId?: string | null;
    onboardingCompletedAt?: NativeDate | null;
    instagramToken?: string | null;
    instagramRefreshToken?: string | null;
    instagramTokenExpiry?: NativeDate | null;
    instagramAccountId?: string | null;
    instagramUsername?: string | null;
    lastApiCallTimestamp?: NativeDate | null;
    rateLimitResetAt?: NativeDate | null;
}, {}, mongoose.DefaultSchemaOptions> & {
    status: string;
    username: string;
    email: string;
    credits: number;
    plan: string;
    totalReferrals: number;
    totalEarned: number;
    isOnboarded: boolean;
    hasUsedWaitlistBonus: boolean;
    dailyLoginStreak: number;
    isEmailVerified: boolean;
    onboardingStep: number;
    onboardingData: any;
    preferences: any;
    goals: any;
    socialPlatforms: any;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    tokenStatus: "active" | "expired" | "rate_limited" | "invalid";
    apiCallCount: number;
    firebaseUid?: string | null;
    displayName?: string | null;
    avatar?: string | null;
    stripeCustomerId?: string | null;
    stripeSubscriptionId?: string | null;
    referralCode?: string | null;
    referredBy?: string | null;
    trialExpiresAt?: NativeDate | null;
    discountCode?: string | null;
    discountExpiresAt?: NativeDate | null;
    lastLoginAt?: NativeDate | null;
    feedbackSubmittedAt?: NativeDate | null;
    emailVerificationCode?: string | null;
    emailVerificationExpiry?: NativeDate | null;
    niche?: string | null;
    targetAudience?: string | null;
    contentStyle?: string | null;
    postingFrequency?: string | null;
    businessType?: string | null;
    experienceLevel?: string | null;
    primaryObjective?: string | null;
    workspaceId?: string | null;
    onboardingCompletedAt?: NativeDate | null;
    instagramToken?: string | null;
    instagramRefreshToken?: string | null;
    instagramTokenExpiry?: NativeDate | null;
    instagramAccountId?: string | null;
    instagramUsername?: string | null;
    lastApiCallTimestamp?: NativeDate | null;
    rateLimitResetAt?: NativeDate | null;
} & {
    _id: mongoose.Types.ObjectId;
} & {
    __v: number;
}, mongoose.Schema<any, mongoose.Model<any, any, any, any, any, any>, {}, {}, {}, {}, mongoose.DefaultSchemaOptions, {
    status: string;
    username: string;
    email: string;
    credits: number;
    plan: string;
    totalReferrals: number;
    totalEarned: number;
    isOnboarded: boolean;
    hasUsedWaitlistBonus: boolean;
    dailyLoginStreak: number;
    isEmailVerified: boolean;
    onboardingStep: number;
    onboardingData: any;
    preferences: any;
    goals: any;
    socialPlatforms: any;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    tokenStatus: "active" | "expired" | "rate_limited" | "invalid";
    apiCallCount: number;
    firebaseUid?: string | null;
    displayName?: string | null;
    avatar?: string | null;
    stripeCustomerId?: string | null;
    stripeSubscriptionId?: string | null;
    referralCode?: string | null;
    referredBy?: string | null;
    trialExpiresAt?: NativeDate | null;
    discountCode?: string | null;
    discountExpiresAt?: NativeDate | null;
    lastLoginAt?: NativeDate | null;
    feedbackSubmittedAt?: NativeDate | null;
    emailVerificationCode?: string | null;
    emailVerificationExpiry?: NativeDate | null;
    niche?: string | null;
    targetAudience?: string | null;
    contentStyle?: string | null;
    postingFrequency?: string | null;
    businessType?: string | null;
    experienceLevel?: string | null;
    primaryObjective?: string | null;
    workspaceId?: string | null;
    onboardingCompletedAt?: NativeDate | null;
    instagramToken?: string | null;
    instagramRefreshToken?: string | null;
    instagramTokenExpiry?: NativeDate | null;
    instagramAccountId?: string | null;
    instagramUsername?: string | null;
    lastApiCallTimestamp?: NativeDate | null;
    rateLimitResetAt?: NativeDate | null;
}, mongoose.Document<unknown, {}, mongoose.FlatRecord<{
    status: string;
    username: string;
    email: string;
    credits: number;
    plan: string;
    totalReferrals: number;
    totalEarned: number;
    isOnboarded: boolean;
    hasUsedWaitlistBonus: boolean;
    dailyLoginStreak: number;
    isEmailVerified: boolean;
    onboardingStep: number;
    onboardingData: any;
    preferences: any;
    goals: any;
    socialPlatforms: any;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    tokenStatus: "active" | "expired" | "rate_limited" | "invalid";
    apiCallCount: number;
    firebaseUid?: string | null;
    displayName?: string | null;
    avatar?: string | null;
    stripeCustomerId?: string | null;
    stripeSubscriptionId?: string | null;
    referralCode?: string | null;
    referredBy?: string | null;
    trialExpiresAt?: NativeDate | null;
    discountCode?: string | null;
    discountExpiresAt?: NativeDate | null;
    lastLoginAt?: NativeDate | null;
    feedbackSubmittedAt?: NativeDate | null;
    emailVerificationCode?: string | null;
    emailVerificationExpiry?: NativeDate | null;
    niche?: string | null;
    targetAudience?: string | null;
    contentStyle?: string | null;
    postingFrequency?: string | null;
    businessType?: string | null;
    experienceLevel?: string | null;
    primaryObjective?: string | null;
    workspaceId?: string | null;
    onboardingCompletedAt?: NativeDate | null;
    instagramToken?: string | null;
    instagramRefreshToken?: string | null;
    instagramTokenExpiry?: NativeDate | null;
    instagramAccountId?: string | null;
    instagramUsername?: string | null;
    lastApiCallTimestamp?: NativeDate | null;
    rateLimitResetAt?: NativeDate | null;
}>, {}, mongoose.ResolveSchemaOptions<mongoose.DefaultSchemaOptions>> & mongoose.FlatRecord<{
    status: string;
    username: string;
    email: string;
    credits: number;
    plan: string;
    totalReferrals: number;
    totalEarned: number;
    isOnboarded: boolean;
    hasUsedWaitlistBonus: boolean;
    dailyLoginStreak: number;
    isEmailVerified: boolean;
    onboardingStep: number;
    onboardingData: any;
    preferences: any;
    goals: any;
    socialPlatforms: any;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    tokenStatus: "active" | "expired" | "rate_limited" | "invalid";
    apiCallCount: number;
    firebaseUid?: string | null;
    displayName?: string | null;
    avatar?: string | null;
    stripeCustomerId?: string | null;
    stripeSubscriptionId?: string | null;
    referralCode?: string | null;
    referredBy?: string | null;
    trialExpiresAt?: NativeDate | null;
    discountCode?: string | null;
    discountExpiresAt?: NativeDate | null;
    lastLoginAt?: NativeDate | null;
    feedbackSubmittedAt?: NativeDate | null;
    emailVerificationCode?: string | null;
    emailVerificationExpiry?: NativeDate | null;
    niche?: string | null;
    targetAudience?: string | null;
    contentStyle?: string | null;
    postingFrequency?: string | null;
    businessType?: string | null;
    experienceLevel?: string | null;
    primaryObjective?: string | null;
    workspaceId?: string | null;
    onboardingCompletedAt?: NativeDate | null;
    instagramToken?: string | null;
    instagramRefreshToken?: string | null;
    instagramTokenExpiry?: NativeDate | null;
    instagramAccountId?: string | null;
    instagramUsername?: string | null;
    lastApiCallTimestamp?: NativeDate | null;
    rateLimitResetAt?: NativeDate | null;
}> & {
    _id: mongoose.Types.ObjectId;
} & {
    __v: number;
}>>;
declare const WorkspaceModel: mongoose.Model<{
    name: string;
    credits: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    userId: any;
    theme: string;
    aiPersonality: string;
    isDefault: boolean;
    maxTeamMembers: number;
    avatar?: string | null;
    description?: string | null;
    inviteCode?: string | null;
}, {}, {}, {}, mongoose.Document<unknown, {}, {
    name: string;
    credits: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    userId: any;
    theme: string;
    aiPersonality: string;
    isDefault: boolean;
    maxTeamMembers: number;
    avatar?: string | null;
    description?: string | null;
    inviteCode?: string | null;
}, {}, mongoose.DefaultSchemaOptions> & {
    name: string;
    credits: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    userId: any;
    theme: string;
    aiPersonality: string;
    isDefault: boolean;
    maxTeamMembers: number;
    avatar?: string | null;
    description?: string | null;
    inviteCode?: string | null;
} & {
    _id: mongoose.Types.ObjectId;
} & {
    __v: number;
}, mongoose.Schema<any, mongoose.Model<any, any, any, any, any, any>, {}, {}, {}, {}, mongoose.DefaultSchemaOptions, {
    name: string;
    credits: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    userId: any;
    theme: string;
    aiPersonality: string;
    isDefault: boolean;
    maxTeamMembers: number;
    avatar?: string | null;
    description?: string | null;
    inviteCode?: string | null;
}, mongoose.Document<unknown, {}, mongoose.FlatRecord<{
    name: string;
    credits: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    userId: any;
    theme: string;
    aiPersonality: string;
    isDefault: boolean;
    maxTeamMembers: number;
    avatar?: string | null;
    description?: string | null;
    inviteCode?: string | null;
}>, {}, mongoose.ResolveSchemaOptions<mongoose.DefaultSchemaOptions>> & mongoose.FlatRecord<{
    name: string;
    credits: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    userId: any;
    theme: string;
    aiPersonality: string;
    isDefault: boolean;
    maxTeamMembers: number;
    avatar?: string | null;
    description?: string | null;
    inviteCode?: string | null;
}> & {
    _id: mongoose.Types.ObjectId;
} & {
    __v: number;
}>>;
declare const SocialAccountModel: mongoose.Model<{
    username: string;
    totalLikes: number;
    totalComments: number;
    totalShares: number;
    totalSaves: number;
    totalReach: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    workspaceId: any;
    platform: string;
    isActive: boolean;
    followersCount: number;
    followingCount: number;
    mediaCount: number;
    accountType: string;
    isBusinessAccount: boolean;
    isVerified: boolean;
    avgEngagement: number;
    engagementRate: number;
    encryptedAccessToken: any;
    encryptedRefreshToken: any;
    avgLikes: number;
    avgComments: number;
    avgReach: number;
    totalReplies: number;
    postsAnalyzed: number;
    accountLevelReach: number;
    postLevelReach: number;
    reachSource: string;
    reachByPeriod: any;
    biography?: string | null;
    website?: string | null;
    expiresAt?: NativeDate | null;
    accountId?: string | null;
    accessToken?: string | null;
    refreshToken?: string | null;
    profilePictureUrl?: string | null;
    lastSyncAt?: NativeDate | null;
    pageId?: string | null;
}, {}, {}, {}, mongoose.Document<unknown, {}, {
    username: string;
    totalLikes: number;
    totalComments: number;
    totalShares: number;
    totalSaves: number;
    totalReach: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    workspaceId: any;
    platform: string;
    isActive: boolean;
    followersCount: number;
    followingCount: number;
    mediaCount: number;
    accountType: string;
    isBusinessAccount: boolean;
    isVerified: boolean;
    avgEngagement: number;
    engagementRate: number;
    encryptedAccessToken: any;
    encryptedRefreshToken: any;
    avgLikes: number;
    avgComments: number;
    avgReach: number;
    totalReplies: number;
    postsAnalyzed: number;
    accountLevelReach: number;
    postLevelReach: number;
    reachSource: string;
    reachByPeriod: any;
    biography?: string | null;
    website?: string | null;
    expiresAt?: NativeDate | null;
    accountId?: string | null;
    accessToken?: string | null;
    refreshToken?: string | null;
    profilePictureUrl?: string | null;
    lastSyncAt?: NativeDate | null;
    pageId?: string | null;
}, {}, mongoose.DefaultSchemaOptions> & {
    username: string;
    totalLikes: number;
    totalComments: number;
    totalShares: number;
    totalSaves: number;
    totalReach: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    workspaceId: any;
    platform: string;
    isActive: boolean;
    followersCount: number;
    followingCount: number;
    mediaCount: number;
    accountType: string;
    isBusinessAccount: boolean;
    isVerified: boolean;
    avgEngagement: number;
    engagementRate: number;
    encryptedAccessToken: any;
    encryptedRefreshToken: any;
    avgLikes: number;
    avgComments: number;
    avgReach: number;
    totalReplies: number;
    postsAnalyzed: number;
    accountLevelReach: number;
    postLevelReach: number;
    reachSource: string;
    reachByPeriod: any;
    biography?: string | null;
    website?: string | null;
    expiresAt?: NativeDate | null;
    accountId?: string | null;
    accessToken?: string | null;
    refreshToken?: string | null;
    profilePictureUrl?: string | null;
    lastSyncAt?: NativeDate | null;
    pageId?: string | null;
} & {
    _id: mongoose.Types.ObjectId;
} & {
    __v: number;
}, mongoose.Schema<any, mongoose.Model<any, any, any, any, any, any>, {}, {}, {}, {}, mongoose.DefaultSchemaOptions, {
    username: string;
    totalLikes: number;
    totalComments: number;
    totalShares: number;
    totalSaves: number;
    totalReach: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    workspaceId: any;
    platform: string;
    isActive: boolean;
    followersCount: number;
    followingCount: number;
    mediaCount: number;
    accountType: string;
    isBusinessAccount: boolean;
    isVerified: boolean;
    avgEngagement: number;
    engagementRate: number;
    encryptedAccessToken: any;
    encryptedRefreshToken: any;
    avgLikes: number;
    avgComments: number;
    avgReach: number;
    totalReplies: number;
    postsAnalyzed: number;
    accountLevelReach: number;
    postLevelReach: number;
    reachSource: string;
    reachByPeriod: any;
    biography?: string | null;
    website?: string | null;
    expiresAt?: NativeDate | null;
    accountId?: string | null;
    accessToken?: string | null;
    refreshToken?: string | null;
    profilePictureUrl?: string | null;
    lastSyncAt?: NativeDate | null;
    pageId?: string | null;
}, mongoose.Document<unknown, {}, mongoose.FlatRecord<{
    username: string;
    totalLikes: number;
    totalComments: number;
    totalShares: number;
    totalSaves: number;
    totalReach: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    workspaceId: any;
    platform: string;
    isActive: boolean;
    followersCount: number;
    followingCount: number;
    mediaCount: number;
    accountType: string;
    isBusinessAccount: boolean;
    isVerified: boolean;
    avgEngagement: number;
    engagementRate: number;
    encryptedAccessToken: any;
    encryptedRefreshToken: any;
    avgLikes: number;
    avgComments: number;
    avgReach: number;
    totalReplies: number;
    postsAnalyzed: number;
    accountLevelReach: number;
    postLevelReach: number;
    reachSource: string;
    reachByPeriod: any;
    biography?: string | null;
    website?: string | null;
    expiresAt?: NativeDate | null;
    accountId?: string | null;
    accessToken?: string | null;
    refreshToken?: string | null;
    profilePictureUrl?: string | null;
    lastSyncAt?: NativeDate | null;
    pageId?: string | null;
}>, {}, mongoose.ResolveSchemaOptions<mongoose.DefaultSchemaOptions>> & mongoose.FlatRecord<{
    username: string;
    totalLikes: number;
    totalComments: number;
    totalShares: number;
    totalSaves: number;
    totalReach: number;
    createdAt: NativeDate;
    updatedAt: NativeDate;
    workspaceId: any;
    platform: string;
    isActive: boolean;
    followersCount: number;
    followingCount: number;
    mediaCount: number;
    accountType: string;
    isBusinessAccount: boolean;
    isVerified: boolean;
    avgEngagement: number;
    engagementRate: number;
    encryptedAccessToken: any;
    encryptedRefreshToken: any;
    avgLikes: number;
    avgComments: number;
    avgReach: number;
    totalReplies: number;
    postsAnalyzed: number;
    accountLevelReach: number;
    postLevelReach: number;
    reachSource: string;
    reachByPeriod: any;
    biography?: string | null;
    website?: string | null;
    expiresAt?: NativeDate | null;
    accountId?: string | null;
    accessToken?: string | null;
    refreshToken?: string | null;
    profilePictureUrl?: string | null;
    lastSyncAt?: NativeDate | null;
    pageId?: string | null;
}> & {
    _id: mongoose.Types.ObjectId;
} & {
    __v: number;
}>>;
export declare class MongoStorage implements IStorage {
    private isConnected;
    /**
     * Securely store a social media token by encrypting it
     */
    private encryptAndStoreToken;
    /**
     * Securely retrieve and decrypt a social media token with comprehensive error handling
     */
    private decryptStoredToken;
    /**
     * Get access token from social media account.
     * If a legacy plain token exists, seamlessly migrate it to encrypted storage
     * and remove the legacy field. Always returns the decrypted encrypted token.
     */
    getAccessTokenFromAccount(account: any): Promise<string | null>;
    /**
     * Get refresh token from social account.
     * Seamlessly migrates legacy refresh tokens to encrypted storage when found.
     */
    private getRefreshTokenFromAccount;
    connect(): Promise<unknown>;
    getUser(id: number | string): Promise<User | undefined>;
    getUserByFirebaseUid(firebaseUid: string): Promise<User | undefined>;
    getUserByFirebaseId(firebaseId: string): Promise<User | undefined>;
    updateUserLastLogin(firebaseId: string): Promise<void>;
    getUserByEmail(email: string): Promise<User | undefined>;
    getUserByUsername(username: string): Promise<User | undefined>;
    getUserByReferralCode(referralCode: string): Promise<User | undefined>;
    createUser(userData: InsertUser): Promise<User>;
    updateUser(id: number | string, updates: Partial<User>): Promise<User>;
    updateUserCredits(id: number | string, credits: number): Promise<User>;
    getUserCredits(userId: number | string): Promise<number>;
    updateUserStripeInfo(id: number | string, stripeCustomerId: string, stripeSubscriptionId?: string): Promise<User>;
    getWorkspace(id: number | string): Promise<Workspace | undefined>;
    getWorkspacesByUserId(userId: number | string): Promise<Workspace[]>;
    getDefaultWorkspace(userId: number | string): Promise<Workspace | undefined>;
    createWorkspace(workspaceData: InsertWorkspace): Promise<Workspace>;
    updateWorkspace(id: number | string, updates: Partial<Workspace>): Promise<Workspace>;
    updateWorkspaceCredits(id: number | string, credits: number): Promise<void>;
    deleteWorkspace(id: number | string): Promise<void>;
    getAllWorkspaces(): Promise<Workspace[]>;
    setDefaultWorkspace(userId: number | string, workspaceId: number | string): Promise<void>;
    private convertUser;
    private convertWorkspace;
    private convertAnalytics;
    private convertContent;
    private convertSocialAccount;
    getSocialAccount(id: number | string): Promise<SocialAccount | undefined>;
    getSocialAccountByWorkspaceAndPlatform(workspaceId: number, platform: string): Promise<SocialAccount | undefined>;
    getAllConnectedAccounts(): Promise<SocialAccount[]>;
    getSocialAccountsByWorkspace(workspaceId: any): Promise<SocialAccount[]>;
    /**
     * INTERNAL USE ONLY: Get social accounts with decrypted tokens
     * This method exposes actual tokens and should ONLY be used by internal services
     * like auto-sync, NOT for API responses to clients
     */
    getSocialAccountsWithTokensInternal(workspaceId: string): Promise<any[]>;
    getAllSocialAccounts(): Promise<SocialAccount[]>;
    getSocialAccountByPlatform(workspaceId: number | string, platform: string): Promise<SocialAccount | undefined>;
    getSocialAccountByPageId(pageId: string): Promise<SocialAccount | undefined>;
    getSocialConnections(userId: number | string): Promise<SocialAccount[]>;
    createSocialAccount(account: InsertSocialAccount): Promise<SocialAccount>;
    updateSocialAccount(id: number | string, updates: Partial<SocialAccount>): Promise<SocialAccount>;
    deleteSocialAccount(id: number | string): Promise<void>;
    getContent(id: number): Promise<Content | undefined>;
    getContentByWorkspace(workspaceId: number, limit?: number): Promise<Content[]>;
    getScheduledContent(workspaceId?: number): Promise<Content[]>;
    createContent(content: InsertContent): Promise<Content>;
    updateContent(id: number, updates: Partial<Content>): Promise<Content>;
    createPost(postData: any): Promise<any>;
    deleteContent(id: number | string): Promise<void>;
    getAnalytics(workspaceId: number | string, platform?: string, days?: number): Promise<Analytics[]>;
    createAnalytics(analytics: InsertAnalytics): Promise<Analytics>;
    getLatestAnalytics(workspaceId: number, platform: string): Promise<Analytics | undefined>;
    getAutomationRules(workspaceId: number | string): Promise<AutomationRule[]>;
    getActiveAutomationRules(): Promise<AutomationRule[]>;
    getAutomationRulesByType(type: string): Promise<AutomationRule[]>;
    createAutomationRule(rule: InsertAutomationRule): Promise<AutomationRule>;
    updateAutomationRule(id: string, updates: Partial<AutomationRule>): Promise<AutomationRule>;
    deleteAutomationRule(id: string): Promise<void>;
    clearWorkspaceConversations(workspaceId: string): Promise<void>;
    getSuggestions(workspaceId: number, type?: string): Promise<Suggestion[]>;
    getValidSuggestions(workspaceId: number): Promise<Suggestion[]>;
    createSuggestion(suggestion: InsertSuggestion): Promise<Suggestion>;
    markSuggestionUsed(id: number): Promise<Suggestion>;
    clearSuggestionsByWorkspace(workspaceId: string | number): Promise<void>;
    getCreditTransactions(userId: number, limit?: number): Promise<CreditTransaction[]>;
    createCreditTransaction(transaction: InsertCreditTransaction): Promise<CreditTransaction>;
    getReferrals(referrerId: number): Promise<Referral[]>;
    getReferralStats(userId: number): Promise<{
        totalReferrals: number;
        activePaid: number;
        totalEarned: number;
    }>;
    createReferral(referral: InsertReferral): Promise<Referral>;
    confirmReferral(id: number): Promise<Referral>;
    getLeaderboard(limit?: number): Promise<Array<User & {
        referralCount: number;
    }>>;
    getSubscription(userId: number): Promise<Subscription | undefined>;
    createSubscription(insertSubscription: InsertSubscription): Promise<Subscription>;
    updateSubscriptionStatus(userId: number, status: string, canceledAt?: Date): Promise<Subscription>;
    getActiveSubscription(userId: number): Promise<Subscription | undefined>;
    createPayment(insertPayment: InsertPayment): Promise<Payment>;
    getPaymentsByUser(userId: number): Promise<Payment[]>;
    getUserAddons(userId: number | string): Promise<Addon[]>;
    getActiveAddonsByUser(userId: number | string): Promise<Addon[]>;
    createAddon(insertAddon: InsertAddon): Promise<Addon>;
    private convertSubscription;
    private convertPayment;
    getSuggestionsByWorkspace(workspaceId: string | number): Promise<Suggestion[]>;
    getAnalyticsByWorkspace(workspaceId: string | number): Promise<Analytics[]>;
    private convertSuggestion;
    private convertAddon;
    getWorkspaceByInviteCode(inviteCode: string): Promise<Workspace | undefined>;
    getWorkspaceMember(workspaceId: number | string, userId: number | string): Promise<WorkspaceMember | undefined>;
    getWorkspaceMembers(workspaceId: number | string): Promise<(WorkspaceMember & {
        user: User;
    })[]>;
    addWorkspaceMember(member: InsertWorkspaceMember): Promise<WorkspaceMember>;
    updateWorkspaceMember(workspaceId: number | string, userId: number | string, updates: Partial<WorkspaceMember>): Promise<WorkspaceMember>;
    removeWorkspaceMember(workspaceId: number | string, userId: number | string): Promise<void>;
    createTeamInvitation(invitation: InsertTeamInvitation): Promise<TeamInvitation>;
    getWorkspaceInvitations(workspaceId: number): Promise<TeamInvitation[]>;
    getTeamInvitation(id: number): Promise<TeamInvitation | undefined>;
    getTeamInvitationByToken(token: string): Promise<TeamInvitation | undefined>;
    getTeamInvitations(workspaceId: number | string, status?: string): Promise<TeamInvitation[]>;
    updateTeamInvitation(id: number, updates: Partial<TeamInvitation>): Promise<TeamInvitation>;
    private convertWorkspaceMember;
    private convertTeamInvitation;
    getContentRecommendation(id: number): Promise<ContentRecommendation | undefined>;
    getContentRecommendations(workspaceId: number, type?: string, limit?: number): Promise<ContentRecommendation[]>;
    createContentRecommendation(insertRecommendation: InsertContentRecommendation): Promise<ContentRecommendation>;
    updateContentRecommendation(id: number, updates: Partial<ContentRecommendation>): Promise<ContentRecommendation>;
    deleteContentRecommendation(id: number): Promise<void>;
    getUserContentHistory(userId: number, workspaceId: number): Promise<UserContentHistory[]>;
    createUserContentHistory(insertHistory: InsertUserContentHistory): Promise<UserContentHistory>;
    private convertContentRecommendation;
    private convertUserContentHistory;
    getPricingData(): Promise<any>;
    updateUserSubscription(userId: number | string, planId: string): Promise<User>;
    addCreditsToUser(userId: number | string, credits: number): Promise<User>;
    getDmConversation(workspaceId: string, platform: string, participantId: string): Promise<any>;
    createDmConversation(data: any): Promise<any>;
    createDmMessage(data: any): Promise<any>;
    updateConversationLastMessage(conversationId: string | number): Promise<void>;
    getDmMessages(conversationId: number | string, limit?: number): Promise<any[]>;
    getConversationContext(conversationId: number): Promise<any[]>;
    createConversationContext(data: any): Promise<any>;
    cleanupExpiredContext(cutoffDate: Date): Promise<void>;
    cleanupOldMessages(cutoffDate: Date): Promise<void>;
    getConversationStats(workspaceId: string): Promise<{
        totalConversations: number;
        activeConversations: number;
        totalMessages: number;
        averageResponseTime: number;
    }>;
    getDmConversations(workspaceId: string, limit?: number): Promise<any[]>;
    getAutomationRulesByTrigger(triggerType: string): Promise<any[]>;
    getAdmin(id: number): Promise<Admin | undefined>;
    getAdminByEmail(email: string): Promise<Admin | undefined>;
    getAdminByUsername(username: string): Promise<Admin | undefined>;
    getAllAdmins(): Promise<Admin[]>;
    createAdmin(admin: InsertAdmin): Promise<Admin>;
    updateAdmin(id: number, updates: Partial<Admin>): Promise<Admin>;
    deleteAdmin(id: number): Promise<void>;
    getAdminUsers(options: {
        page: number;
        limit: number;
        search?: string;
        filter?: string;
    }): Promise<any>;
    createAdminSession(session: any): Promise<any>;
    getAdminSession(token: string): Promise<any | undefined>;
    deleteAdminSession(token: string): Promise<void>;
    cleanupExpiredSessions(): Promise<void>;
    createNotification(notification: any): Promise<any>;
    getUserNotifications(userId: string): Promise<any[]>;
    markNotificationAsRead(notificationId: string, userId: string): Promise<void>;
    getNotifications(userId?: number): Promise<any[]>;
    updateNotification(id: number, updates: Partial<any>): Promise<any>;
    deleteNotification(id: number): Promise<void>;
    markNotificationRead(id: number): Promise<void>;
    createPopup(popup: any): Promise<any>;
    getActivePopups(): Promise<any[]>;
    getPopup(id: number): Promise<any | undefined>;
    updatePopup(id: number, updates: Partial<any>): Promise<any>;
    deletePopup(id: number): Promise<void>;
    createAppSetting(setting: any): Promise<any>;
    getAppSetting(key: string): Promise<any | undefined>;
    getAllAppSettings(): Promise<any[]>;
    getPublicAppSettings(): Promise<any[]>;
    updateAppSetting(key: string, value: string, updatedBy?: number): Promise<any>;
    deleteAppSetting(key: string): Promise<void>;
    createAuditLog(log: any): Promise<any>;
    getAuditLogs(limit?: number, adminId?: number): Promise<any[]>;
    createFeedbackMessage(feedback: any): Promise<any>;
    getFeedbackMessages(status?: string): Promise<any[]>;
    updateFeedbackMessage(id: number, updates: Partial<any>): Promise<any>;
    deleteFeedbackMessage(id: number): Promise<void>;
    getAutomationLogs(limit?: number): Promise<any[]>;
    createAutomationLog(log: any): Promise<any>;
    getAllUsers(): Promise<any[]>;
    getAdminStats(): Promise<any>;
    private convertAdmin;
    private convertAdminSession;
    private convertNotification;
    private convertPopup;
    private convertAppSetting;
    private convertAuditLog;
    private convertFeedbackMessage;
    storeEmailVerificationCode(email: string, code: string, expiry: Date): Promise<void>;
    verifyEmailCode(email: string, code: string): Promise<boolean>;
    clearEmailVerificationCode(email: string): Promise<void>;
    createUnverifiedUser(data: {
        email: string;
        firstName: string;
        emailVerificationCode: string;
        emailVerificationExpiry: Date;
        isEmailVerified: boolean;
    }): Promise<User>;
    updateUserEmailVerification(id: number | string, token: string, expires: Date): Promise<User>;
    updateYouTubeWorkspaceData(updates: any): Promise<any>;
    verifyUserEmail(id: number | string, data: {
        password?: string;
        firstName?: string;
        lastName?: string;
        firebaseUid?: string;
    }): Promise<User>;
    createThumbnailProject(data: any): Promise<any>;
    getThumbnailProject(projectId: number): Promise<any>;
    updateThumbnailProject(projectId: number, updates: any): Promise<void>;
    getThumbnailProjects(workspaceId: number): Promise<any[]>;
    createThumbnailStrategy(data: any): Promise<any>;
    getThumbnailStrategy(projectId: number): Promise<any>;
    createThumbnailVariant(data: any): Promise<any>;
    getThumbnailVariant(variantId: number): Promise<any>;
    getThumbnailVariants(projectId: number): Promise<any[]>;
    createCanvasEditorSession(data: any): Promise<any>;
    getCanvasEditorSession(sessionId: number): Promise<any>;
    updateCanvasEditorSession(sessionId: number, updates: any): Promise<void>;
    createThumbnailExport(data: any): Promise<any>;
    getThumbnailExports(sessionId: number): Promise<any[]>;
    incrementExportDownload(exportId: number): Promise<void>;
    createCreativeBrief(brief: InsertCreativeBrief): Promise<CreativeBrief>;
    getCreativeBrief(id: number): Promise<CreativeBrief | undefined>;
    getCreativeBriefsByWorkspace(workspaceId: number): Promise<CreativeBrief[]>;
    updateCreativeBrief(id: number, updates: Partial<CreativeBrief>): Promise<CreativeBrief>;
    deleteCreativeBrief(id: number): Promise<void>;
    createContentRepurpose(repurpose: InsertContentRepurpose): Promise<ContentRepurpose>;
    getContentRepurpose(id: number): Promise<ContentRepurpose | undefined>;
    getContentRepurposesByWorkspace(workspaceId: number): Promise<ContentRepurpose[]>;
    updateContentRepurpose(id: number, updates: Partial<ContentRepurpose>): Promise<ContentRepurpose>;
    deleteContentRepurpose(id: number): Promise<void>;
    createCompetitorAnalysis(analysis: InsertCompetitorAnalysis): Promise<CompetitorAnalysis>;
    getCompetitorAnalysis(id: number): Promise<CompetitorAnalysis | undefined>;
    getCompetitorAnalysesByWorkspace(workspaceId: number): Promise<CompetitorAnalysis[]>;
    updateCompetitorAnalysis(id: number, updates: Partial<CompetitorAnalysis>): Promise<CompetitorAnalysis>;
    deleteCompetitorAnalysis(id: number): Promise<void>;
    private convertCreativeBrief;
    private convertContentRepurpose;
    private convertCompetitorAnalysis;
    getFeatureUsage(userId: number | string): Promise<any[]>;
    trackFeatureUsage(userId: number | string, featureId: string, usage: any): Promise<void>;
    createWaitlistUser(insertWaitlistUser: InsertWaitlistUser): Promise<WaitlistUser>;
    getWaitlistUser(id: number | string): Promise<WaitlistUser | undefined>;
    getWaitlistUserByEmail(email: string): Promise<WaitlistUser | undefined>;
    getWaitlistUserByReferralCode(referralCode: string): Promise<WaitlistUser | undefined>;
    updateWaitlistUser(id: number | string, updates: Partial<WaitlistUser>): Promise<WaitlistUser>;
    getAllWaitlistUsers(): Promise<WaitlistUser[]>;
    getWaitlistStats(): Promise<{
        totalUsers: number;
        todaySignups: number;
        totalReferrals: number;
        averageReferrals: number;
        statusBreakdown: {
            [key: string]: number;
        };
    }>;
    promoteWaitlistUser(id: number | string): Promise<{
        user: User;
        workspace: Workspace;
        discountCode: string;
        trialDays: number;
    }>;
    private convertWaitlistUser;
    clearAllUsers(): Promise<number>;
    clearAllWaitlistUsers(): Promise<number>;
    deleteWaitlistUser(id: number | string): Promise<void>;
    clearAllWorkspaces(): Promise<number>;
    clearAllSocialAccounts(): Promise<number>;
    clearAllContent(): Promise<number>;
    getChatConversations(userId: string, workspaceId?: string): Promise<ChatConversation[]>;
    createChatConversation(conversation: InsertChatConversation): Promise<ChatConversation>;
    getChatMessages(conversationId: number): Promise<ChatMessage[]>;
    createChatMessage(message: InsertChatMessage): Promise<ChatMessage>;
    updateChatMessage(id: number, updates: Partial<ChatMessage>): Promise<ChatMessage>;
    updateChatConversation(id: string | number, updates: Partial<ChatConversation>): Promise<ChatConversation>;
    deleteChatConversation(id: string | number): Promise<void>;
}
export declare const storage: MongoStorage;
export { UserModel, WorkspaceModel, SocialAccountModel };
