import { type User, type Workspace, type WorkspaceMember, type TeamInvitation, type SocialAccount, type Content, type Analytics, type AutomationRule, type Suggestion, type CreditTransaction, type Referral, type Subscription, type Payment, type Addon, type ContentRecommendation, type UserContentHistory, type Admin, type AdminSession, type Notification, type Popup, type AppSetting, type AuditLog, type FeedbackMessage, type CreativeBrief, type ContentRepurpose, type CompetitorAnalysis, type ChatConversation, type ChatMessage, type InsertUser, type InsertWorkspace, type InsertWorkspaceMember, type InsertTeamInvitation, type InsertSocialAccount, type InsertContent, type InsertAutomationRule, type InsertAnalytics, type InsertSuggestion, type InsertCreditTransaction, type InsertReferral, type InsertSubscription, type InsertPayment, type InsertAddon, type InsertContentRecommendation, type InsertUserContentHistory, type InsertAdmin, type InsertNotification, type InsertPopup, type InsertAppSetting, type InsertAuditLog, type InsertFeedbackMessage, type InsertCreativeBrief, type InsertContentRepurpose, type InsertCompetitorAnalysis, type InsertChatConversation, type InsertChatMessage } from "@shared/schema";
export interface IStorage {
    getUser(id: number | string): Promise<User | undefined>;
    getUserByFirebaseUid(firebaseUid: string): Promise<User | undefined>;
    getUserByEmail(email: string): Promise<User | undefined>;
    getUserByUsername(username: string): Promise<User | undefined>;
    getUserByReferralCode(referralCode: string): Promise<User | undefined>;
    createUser(user: InsertUser): Promise<User>;
    updateUser(id: number | string, updates: Partial<User>): Promise<User>;
    updateUserCredits(id: number | string, credits: number): Promise<User>;
    getUserCredits(userId: number | string): Promise<number>;
    updateUserStripeInfo(id: number | string, stripeCustomerId: string, stripeSubscriptionId?: string): Promise<User>;
    createUnverifiedUser(data: {
        email: string;
        firstName: string;
        emailVerificationCode: string;
        emailVerificationExpiry: Date;
        isEmailVerified: boolean;
    }): Promise<User>;
    updateUserEmailVerification(id: number | string, token: string, expires: Date): Promise<User>;
    verifyUserEmail(id: number | string, data: {
        password?: string;
        firstName?: string;
        lastName?: string;
    }): Promise<User>;
    getWorkspace(id: number | string): Promise<Workspace | undefined>;
    getWorkspacesByUserId(userId: number | string): Promise<Workspace[]>;
    getDefaultWorkspace(userId: number | string): Promise<Workspace | undefined>;
    getWorkspaceByInviteCode(inviteCode: string): Promise<Workspace | undefined>;
    createWorkspace(workspace: InsertWorkspace): Promise<Workspace>;
    updateWorkspace(id: number | string, updates: Partial<Workspace>): Promise<Workspace>;
    updateWorkspaceCredits(id: number | string, credits: number): Promise<void>;
    deleteWorkspace(id: number | string): Promise<void>;
    setDefaultWorkspace(userId: number | string, workspaceId: number | string): Promise<void>;
    getWorkspaceMember(workspaceId: number, userId: number): Promise<WorkspaceMember | undefined>;
    getWorkspaceMembers(workspaceId: number): Promise<(WorkspaceMember & {
        user: User;
    })[]>;
    addWorkspaceMember(member: InsertWorkspaceMember): Promise<WorkspaceMember>;
    updateWorkspaceMember(workspaceId: number, userId: number, updates: Partial<WorkspaceMember>): Promise<WorkspaceMember>;
    removeWorkspaceMember(workspaceId: number, userId: number): Promise<void>;
    createTeamInvitation(invitation: InsertTeamInvitation): Promise<TeamInvitation>;
    getTeamInvitation(id: number): Promise<TeamInvitation | undefined>;
    getTeamInvitationByToken(token: string): Promise<TeamInvitation | undefined>;
    getTeamInvitations(workspaceId: number, status?: string): Promise<TeamInvitation[]>;
    getWorkspaceInvitations(workspaceId: number): Promise<TeamInvitation[]>;
    updateTeamInvitation(id: number, updates: Partial<TeamInvitation>): Promise<TeamInvitation>;
    getSocialAccount(id: number | string): Promise<SocialAccount | undefined>;
    getSocialAccountsByWorkspace(workspaceId: number | string): Promise<SocialAccount[]>;
    getAllSocialAccounts(): Promise<SocialAccount[]>;
    getSocialAccountByPlatform(workspaceId: number | string, platform: string): Promise<SocialAccount | undefined>;
    getSocialAccountByPageId(pageId: string): Promise<SocialAccount | undefined>;
    getSocialConnections(userId: number): Promise<SocialAccount[]>;
    createSocialAccount(account: InsertSocialAccount): Promise<SocialAccount>;
    updateSocialAccount(id: number | string, updates: Partial<SocialAccount>): Promise<SocialAccount>;
    deleteSocialAccount(id: number): Promise<void>;
    getContent(id: number): Promise<Content | undefined>;
    getContentByWorkspace(workspaceId: number | string, limit?: number): Promise<Content[]>;
    getScheduledContent(workspaceId?: number | string): Promise<Content[]>;
    createContent(content: InsertContent): Promise<Content>;
    updateContent(id: number, updates: Partial<Content>): Promise<Content>;
    deleteContent(id: number): Promise<void>;
    createPost(postData: any): Promise<any>;
    getAnalytics(workspaceId: number, platform?: string, days?: number): Promise<Analytics[]>;
    createAnalytics(analytics: InsertAnalytics): Promise<Analytics>;
    getLatestAnalytics(workspaceId: number, platform: string): Promise<Analytics | undefined>;
    getAutomationRule(id: string): Promise<AutomationRule | undefined>;
    getAutomationRules(workspaceId: number | string): Promise<AutomationRule[]>;
    getActiveAutomationRules(): Promise<AutomationRule[]>;
    getAutomationRulesByType(type: string): Promise<AutomationRule[]>;
    createAutomationRule(rule: InsertAutomationRule): Promise<AutomationRule>;
    updateAutomationRule(id: string, updates: Partial<AutomationRule>): Promise<AutomationRule>;
    deleteAutomationRule(id: string): Promise<void>;
    getAutomationLogs(workspaceId: string | number, options?: {
        limit?: number;
        type?: string;
    }): Promise<any[]>;
    createAutomationLog(log: any): Promise<any>;
    getAllSocialAccounts(): Promise<SocialAccount[]>;
    getSuggestions(workspaceId: number, type?: string): Promise<Suggestion[]>;
    getSuggestionsByWorkspace(workspaceId: string | number): Promise<Suggestion[]>;
    getValidSuggestions(workspaceId: number): Promise<Suggestion[]>;
    createSuggestion(suggestion: InsertSuggestion): Promise<Suggestion>;
    markSuggestionUsed(id: number): Promise<Suggestion>;
    clearSuggestionsByWorkspace(workspaceId: string | number): Promise<void>;
    getAnalyticsByWorkspace(workspaceId: string | number): Promise<Analytics[]>;
    getCreditTransactions(userId: number, limit?: number): Promise<CreditTransaction[]>;
    createCreditTransaction(transaction: InsertCreditTransaction): Promise<CreditTransaction>;
    getReferrals(referrerId: number): Promise<Referral[]>;
    getReferralStats(userId: number): Promise<{
        totalReferrals: number;
        activePaid: number;
        totalEarned: number;
    }>;
    createReferral(referral: InsertReferral): Promise<Referral>;
    confirmReferral(id: number): Promise<Referral>;
    getLeaderboard(limit?: number): Promise<Array<User & {
        referralCount: number;
    }>>;
    getSubscription(userId: number): Promise<Subscription | undefined>;
    createSubscription(subscription: InsertSubscription): Promise<Subscription>;
    updateSubscriptionStatus(userId: number, status: string, canceledAt?: Date): Promise<Subscription>;
    createPayment(payment: InsertPayment): Promise<Payment>;
    getPaymentsByUser(userId: number): Promise<Payment[]>;
    getUserAddons(userId: number | string): Promise<Addon[]>;
    getActiveAddonsByUser(userId: number): Promise<Addon[]>;
    createAddon(addon: InsertAddon): Promise<Addon>;
    getFeatureUsage(userId: number | string): Promise<any[]>;
    trackFeatureUsage(userId: number | string, featureId: string, usage: any): Promise<void>;
    getContentRecommendation(id: number): Promise<ContentRecommendation | undefined>;
    getContentRecommendations(workspaceId: number, type?: string, limit?: number): Promise<ContentRecommendation[]>;
    createContentRecommendation(recommendation: InsertContentRecommendation): Promise<ContentRecommendation>;
    updateContentRecommendation(id: number, updates: Partial<ContentRecommendation>): Promise<ContentRecommendation>;
    getUserContentHistory(userId: number, workspaceId: number): Promise<UserContentHistory[]>;
    createUserContentHistory(history: InsertUserContentHistory): Promise<UserContentHistory>;
    getPricingData(): Promise<any>;
    updateUserSubscription(userId: number | string, planId: string): Promise<User>;
    addCreditsToUser(userId: number | string, credits: number): Promise<User>;
    createDmConversation(conversation: any): Promise<any>;
    createDmMessage(message: any): Promise<any>;
    createConversationContext(context: any): Promise<any>;
    clearWorkspaceConversations(workspaceId: string): Promise<void>;
    getDmConversations(workspaceId: string, limit?: number): Promise<any[]>;
    getDmMessages(conversationId: number | string, limit?: number): Promise<any[]>;
    getChatConversations(userId: string, workspaceId?: string): Promise<ChatConversation[]>;
    getChatConversation(id: number): Promise<ChatConversation | undefined>;
    createChatConversation(conversation: InsertChatConversation): Promise<ChatConversation>;
    updateChatConversation(id: number, updates: Partial<ChatConversation>): Promise<ChatConversation>;
    deleteChatConversation(id: number): Promise<void>;
    getChatMessages(conversationId: number): Promise<ChatMessage[]>;
    createChatMessage(message: InsertChatMessage): Promise<ChatMessage>;
    updateChatMessage(id: number, updates: Partial<ChatMessage>): Promise<ChatMessage>;
    getChatMessage(id: number): Promise<ChatMessage | undefined>;
    updateYouTubeWorkspaceData(updates: any): Promise<any>;
    getAdmin(id: number): Promise<Admin | undefined>;
    getAdminByEmail(email: string): Promise<Admin | undefined>;
    getAdminByUsername(username: string): Promise<Admin | undefined>;
    getAllAdmins(): Promise<Admin[]>;
    createAdmin(admin: InsertAdmin): Promise<Admin>;
    updateAdmin(id: number, updates: Partial<Admin>): Promise<Admin>;
    deleteAdmin(id: number): Promise<void>;
    createAdminSession(session: Partial<AdminSession>): Promise<AdminSession>;
    getAdminSession(token: string): Promise<AdminSession | undefined>;
    deleteAdminSession(token: string): Promise<void>;
    cleanupExpiredSessions(): Promise<void>;
    createNotification(notification: InsertNotification): Promise<Notification>;
    getNotifications(userId?: number): Promise<Notification[]>;
    getUserNotifications(userId: string): Promise<any[]>;
    markNotificationAsRead(notificationId: string, userId: string): Promise<void>;
    updateNotification(id: number, updates: Partial<Notification>): Promise<Notification>;
    deleteNotification(id: number): Promise<void>;
    markNotificationRead(id: number): Promise<void>;
    createPopup(popup: InsertPopup): Promise<Popup>;
    getActivePopups(): Promise<Popup[]>;
    getPopup(id: number): Promise<Popup | undefined>;
    updatePopup(id: number, updates: Partial<Popup>): Promise<Popup>;
    deletePopup(id: number): Promise<void>;
    createAppSetting(setting: InsertAppSetting): Promise<AppSetting>;
    getAppSetting(key: string): Promise<AppSetting | undefined>;
    getAllAppSettings(): Promise<AppSetting[]>;
    getPublicAppSettings(): Promise<AppSetting[]>;
    updateAppSetting(key: string, value: string, updatedBy?: number): Promise<AppSetting>;
    deleteAppSetting(key: string): Promise<void>;
    createAuditLog(log: InsertAuditLog): Promise<AuditLog>;
    getAuditLogs(limit?: number, adminId?: number): Promise<AuditLog[]>;
    createFeedbackMessage(feedback: InsertFeedbackMessage): Promise<FeedbackMessage>;
    getFeedbackMessages(status?: string): Promise<FeedbackMessage[]>;
    updateFeedbackMessage(id: number, updates: Partial<FeedbackMessage>): Promise<FeedbackMessage>;
    deleteFeedbackMessage(id: number): Promise<void>;
    getAdminUsers(page?: number, limit?: number, search?: string): Promise<{
        users: User[];
        total: number;
    }>;
    getAdminContent(page?: number, limit?: number, filters?: any): Promise<{
        content: Content[];
        total: number;
    }>;
    getAdminNotifications(page?: number, limit?: number): Promise<{
        notifications: Notification[];
        total: number;
    }>;
    getAdminStats(): Promise<{
        totalUsers: number;
        totalWorkspaces: number;
        totalContent: number;
        totalCreditsUsed: number;
        revenueThisMonth: number;
        activeUsers: number;
    }>;
    createThumbnailProject(project: any): Promise<any>;
    getThumbnailProject(id: number): Promise<any>;
    updateThumbnailProject(id: number, updates: any): Promise<any>;
    createThumbnailStrategy(strategy: any): Promise<any>;
    createThumbnailVariant(variant: any): Promise<any>;
    getThumbnailVariants(projectId: number): Promise<any[]>;
    createCanvasSession(session: any): Promise<any>;
    updateCanvasSession(id: number, updates: any): Promise<any>;
    createThumbnailExport(exportData: any): Promise<any>;
    incrementExportDownload(exportId: number): Promise<void>;
    createCreativeBrief(brief: InsertCreativeBrief): Promise<CreativeBrief>;
    getCreativeBrief(id: number): Promise<CreativeBrief | undefined>;
    getCreativeBriefsByWorkspace(workspaceId: number): Promise<CreativeBrief[]>;
    updateCreativeBrief(id: number, updates: Partial<CreativeBrief>): Promise<CreativeBrief>;
    deleteCreativeBrief(id: number): Promise<void>;
    createContentRepurpose(repurpose: InsertContentRepurpose): Promise<ContentRepurpose>;
    getContentRepurpose(id: number): Promise<ContentRepurpose | undefined>;
    getContentRepurposesByWorkspace(workspaceId: number): Promise<ContentRepurpose[]>;
    updateContentRepurpose(id: number, updates: Partial<ContentRepurpose>): Promise<ContentRepurpose>;
    deleteContentRepurpose(id: number): Promise<void>;
    createCompetitorAnalysis(analysis: InsertCompetitorAnalysis): Promise<CompetitorAnalysis>;
    getCompetitorAnalysis(id: number): Promise<CompetitorAnalysis | undefined>;
    getCompetitorAnalysesByWorkspace(workspaceId: number): Promise<CompetitorAnalysis[]>;
    updateCompetitorAnalysis(id: number, updates: Partial<CompetitorAnalysis>): Promise<CompetitorAnalysis>;
    deleteCompetitorAnalysis(id: number): Promise<void>;
    createWaitlistUser?(insertWaitlistUser: any): Promise<any>;
    getWaitlistUser?(id: number | string): Promise<any>;
    getWaitlistUserByEmail?(email: string): Promise<any>;
    updateWaitlistUser?(id: number | string, updates: any): Promise<any>;
    deleteWaitlistUser?(id: number | string): Promise<void>;
    getAllWaitlistUsers?(): Promise<any[]>;
    getWaitlistStats?(): Promise<any>;
    clearAllWaitlistUsers?(): Promise<number>;
}
export declare class MemStorage implements IStorage {
    private users;
    private workspaces;
    private workspaceMembers;
    private teamInvitations;
    private socialAccounts;
    private content;
    private analytics;
    private automationRules;
    private suggestions;
    private creditTransactions;
    private referrals;
    private subscriptions;
    private payments;
    private addons;
    private contentRecommendations;
    private userContentHistory;
    private chatConversations;
    private chatMessages;
    private currentUserId;
    private currentWorkspaceId;
    private currentWorkspaceMemberId;
    private currentTeamInvitationId;
    private currentSocialAccountId;
    private currentContentId;
    private currentAnalyticsId;
    private currentAutomationRuleId;
    private currentSuggestionId;
    private currentCreditTransactionId;
    private currentReferralId;
    private currentSubscriptionId;
    private currentPaymentId;
    private currentAddonId;
    private currentContentRecommendationId;
    private currentUserContentHistoryId;
    private currentChatConversationId;
    private currentChatMessageId;
    getUser(id: number): Promise<User | undefined>;
    getUserByFirebaseUid(firebaseUid: string): Promise<User | undefined>;
    getUserByEmail(email: string): Promise<User | undefined>;
    getUserByUsername(username: string): Promise<User | undefined>;
    getUserByReferralCode(referralCode: string): Promise<User | undefined>;
    createUser(insertUser: InsertUser): Promise<User>;
    updateUser(id: number | string, updates: Partial<User>): Promise<User>;
    updateUserCredits(id: number, credits: number): Promise<User>;
    updateUserStripeInfo(id: number, stripeCustomerId: string, stripeSubscriptionId?: string): Promise<User>;
    getWorkspace(id: number): Promise<Workspace | undefined>;
    getWorkspacesByUserId(userId: number): Promise<Workspace[]>;
    getDefaultWorkspace(userId: number): Promise<Workspace | undefined>;
    createWorkspace(insertWorkspace: InsertWorkspace): Promise<Workspace>;
    updateWorkspace(id: number, updates: Partial<Workspace>): Promise<Workspace>;
    updateWorkspaceCredits(id: number | string, credits: number): Promise<void>;
    deleteWorkspace(id: number): Promise<void>;
    setDefaultWorkspace(userId: number | string, workspaceId: number | string): Promise<void>;
    getWorkspaceByInviteCode(inviteCode: string): Promise<Workspace | undefined>;
    getWorkspaceMember(workspaceId: number, userId: number): Promise<WorkspaceMember | undefined>;
    getWorkspaceMembers(workspaceId: number): Promise<(WorkspaceMember & {
        user: User;
    })[]>;
    addWorkspaceMember(insertMember: InsertWorkspaceMember): Promise<WorkspaceMember>;
    updateWorkspaceMember(workspaceId: number, userId: number, updates: Partial<WorkspaceMember>): Promise<WorkspaceMember>;
    removeWorkspaceMember(workspaceId: number, userId: number): Promise<void>;
    createTeamInvitation(insertInvitation: InsertTeamInvitation): Promise<TeamInvitation>;
    getTeamInvitation(id: number): Promise<TeamInvitation | undefined>;
    getTeamInvitationByToken(token: string): Promise<TeamInvitation | undefined>;
    getTeamInvitations(workspaceId: number, status?: string): Promise<TeamInvitation[]>;
    getWorkspaceInvitations(workspaceId: number): Promise<TeamInvitation[]>;
    updateTeamInvitation(id: number, updates: Partial<TeamInvitation>): Promise<TeamInvitation>;
    getSocialAccount(id: number): Promise<SocialAccount | undefined>;
    getSocialAccountsByWorkspace(workspaceId: number): Promise<SocialAccount[]>;
    getSocialAccountByPlatform(workspaceId: number | string, platform: string): Promise<SocialAccount | undefined>;
    getSocialConnections(userId: number): Promise<SocialAccount[]>;
    createSocialAccount(insertAccount: InsertSocialAccount): Promise<SocialAccount>;
    updateSocialAccount(id: number | string, updates: Partial<SocialAccount>): Promise<SocialAccount>;
    deleteSocialAccount(id: number): Promise<void>;
    getContent(id: number): Promise<Content | undefined>;
    getContentByWorkspace(workspaceId: number | string, limit?: number): Promise<Content[]>;
    getScheduledContent(workspaceId?: number | string): Promise<Content[]>;
    createContent(insertContent: InsertContent): Promise<Content>;
    updateContent(id: number, updates: Partial<Content>): Promise<Content>;
    deleteContent(id: number): Promise<void>;
    getAnalytics(workspaceId: number, platform?: string, days?: number): Promise<Analytics[]>;
    createAnalytics(insertAnalytics: InsertAnalytics): Promise<Analytics>;
    getLatestAnalytics(workspaceId: number, platform: string): Promise<Analytics | undefined>;
    getAutomationRules(workspaceId: number | string): Promise<AutomationRule[]>;
    getActiveAutomationRules(): Promise<AutomationRule[]>;
    getAutomationRulesByType(type: string): Promise<AutomationRule[]>;
    createAutomationRule(insertRule: InsertAutomationRule): Promise<AutomationRule>;
    updateAutomationRule(id: string, updates: Partial<AutomationRule>): Promise<AutomationRule>;
    deleteAutomationRule(id: string): Promise<void>;
    getAutomationRulesByWorkspace(workspaceId: string | number): Promise<AutomationRule[]>;
    getAutomationLogs(workspaceId: string | number, options?: {
        limit?: number;
        type?: string;
    }): Promise<any[]>;
    createAutomationLog(log: any): Promise<any>;
    getSuggestions(workspaceId: number, type?: string): Promise<Suggestion[]>;
    getValidSuggestions(workspaceId: number): Promise<Suggestion[]>;
    createSuggestion(insertSuggestion: InsertSuggestion): Promise<Suggestion>;
    markSuggestionUsed(id: number): Promise<Suggestion>;
    getSuggestionsByWorkspace(workspaceId: string | number): Promise<Suggestion[]>;
    clearSuggestionsByWorkspace(workspaceId: string | number): Promise<void>;
    getAnalyticsByWorkspace(workspaceId: string | number): Promise<Analytics[]>;
    getCreditTransactions(userId: number, limit?: number): Promise<CreditTransaction[]>;
    createCreditTransaction(insertTransaction: InsertCreditTransaction): Promise<CreditTransaction>;
    getReferrals(referrerId: number): Promise<Referral[]>;
    getReferralStats(userId: number): Promise<{
        totalReferrals: number;
        activePaid: number;
        totalEarned: number;
    }>;
    createReferral(insertReferral: InsertReferral): Promise<Referral>;
    confirmReferral(id: number): Promise<Referral>;
    getLeaderboard(limit?: number): Promise<Array<User & {
        referralCount: number;
    }>>;
    getSubscription(userId: number): Promise<Subscription | undefined>;
    createSubscription(insertSubscription: InsertSubscription): Promise<Subscription>;
    updateSubscriptionStatus(userId: number, status: string, canceledAt?: Date): Promise<Subscription>;
    createPayment(insertPayment: InsertPayment): Promise<Payment>;
    getPaymentsByUser(userId: number): Promise<Payment[]>;
    getUserAddons(userId: number): Promise<Addon[]>;
    getActiveAddonsByUser(userId: number): Promise<Addon[]>;
    createAddon(insertAddon: InsertAddon): Promise<Addon>;
    getContentRecommendation(id: number): Promise<ContentRecommendation | undefined>;
    getContentRecommendations(workspaceId: number, type?: string, limit?: number): Promise<ContentRecommendation[]>;
    createContentRecommendation(insertRecommendation: InsertContentRecommendation): Promise<ContentRecommendation>;
    updateContentRecommendation(id: number, updates: Partial<ContentRecommendation>): Promise<ContentRecommendation>;
    getUserContentHistory(userId: number, workspaceId: number): Promise<UserContentHistory[]>;
    createUserContentHistory(insertHistory: InsertUserContentHistory): Promise<UserContentHistory>;
    getPricingData(): Promise<any>;
    updateUserSubscription(userId: number | string, planId: string): Promise<User>;
    addCreditsToUser(userId: number | string, credits: number): Promise<User>;
    createDmConversation(conversation: any): Promise<any>;
    createDmMessage(message: any): Promise<any>;
    createConversationContext(context: any): Promise<any>;
    clearWorkspaceConversations(workspaceId: string): Promise<void>;
    getDmConversations(workspaceId: string, limit?: number): Promise<any[]>;
    getDmMessages(conversationId: number | string, limit?: number): Promise<any[]>;
    getAdmin(id: number): Promise<Admin | undefined>;
    getAdminByEmail(email: string): Promise<Admin | undefined>;
    getAdminByUsername(username: string): Promise<Admin | undefined>;
    getAllAdmins(): Promise<Admin[]>;
    createAdmin(admin: InsertAdmin): Promise<Admin>;
    updateAdmin(id: number, updates: Partial<Admin>): Promise<Admin>;
    deleteAdmin(id: number): Promise<void>;
    createAdminSession(session: Partial<AdminSession>): Promise<AdminSession>;
    getAdminSession(token: string): Promise<AdminSession | undefined>;
    deleteAdminSession(token: string): Promise<void>;
    cleanupExpiredSessions(): Promise<void>;
    createNotification(notification: InsertNotification): Promise<Notification>;
    getNotifications(userId?: number): Promise<Notification[]>;
    updateNotification(id: number, updates: Partial<Notification>): Promise<Notification>;
    deleteNotification(id: number): Promise<void>;
    markNotificationRead(id: number): Promise<void>;
    createPopup(popup: InsertPopup): Promise<Popup>;
    getActivePopups(): Promise<Popup[]>;
    getPopup(id: number): Promise<Popup | undefined>;
    updatePopup(id: number, updates: Partial<Popup>): Promise<Popup>;
    deletePopup(id: number): Promise<void>;
    createAppSetting(setting: InsertAppSetting): Promise<AppSetting>;
    getAppSetting(key: string): Promise<AppSetting | undefined>;
    getAllAppSettings(): Promise<AppSetting[]>;
    getPublicAppSettings(): Promise<AppSetting[]>;
    updateAppSetting(key: string, value: string, updatedBy?: number): Promise<AppSetting>;
    deleteAppSetting(key: string): Promise<void>;
    createAuditLog(log: InsertAuditLog): Promise<AuditLog>;
    getAuditLogs(limit?: number, adminId?: number): Promise<AuditLog[]>;
    createFeedbackMessage(feedback: InsertFeedbackMessage): Promise<FeedbackMessage>;
    getFeedbackMessages(status?: string): Promise<FeedbackMessage[]>;
    updateFeedbackMessage(id: number, updates: Partial<FeedbackMessage>): Promise<FeedbackMessage>;
    deleteFeedbackMessage(id: number): Promise<void>;
    getAdminStats(): Promise<{
        totalUsers: number;
        totalWorkspaces: number;
        totalContent: number;
        totalCreditsUsed: number;
        revenueThisMonth: number;
        activeUsers: number;
    }>;
    getAdminUsers(page?: number, limit?: number, search?: string): Promise<{
        users: User[];
        total: number;
    }>;
    getAdminContent(page?: number, limit?: number, filters?: any): Promise<{
        content: Content[];
        total: number;
    }>;
    getAdminNotifications(page?: number, limit?: number): Promise<{
        notifications: Notification[];
        total: number;
    }>;
    createThumbnailProject(project: any): Promise<any>;
    getThumbnailProject(id: number): Promise<any>;
    updateThumbnailProject(id: number, updates: any): Promise<any>;
    createThumbnailStrategy(strategy: any): Promise<any>;
    createThumbnailVariant(variant: any): Promise<any>;
    getThumbnailVariants(projectId: number): Promise<any[]>;
    createCanvasSession(session: any): Promise<any>;
    updateCanvasSession(id: number, updates: any): Promise<any>;
    createThumbnailExport(exportData: any): Promise<any>;
    incrementExportDownload(exportId: number): Promise<void>;
    getFeatureUsage(userId: number | string): Promise<any[]>;
    trackFeatureUsage(userId: number | string, featureId: string, usage: any): Promise<void>;
    getChatConversations(userId: number, workspaceId: number): Promise<ChatConversation[]>;
    getChatConversation(id: number): Promise<ChatConversation | undefined>;
    createChatConversation(conversation: InsertChatConversation): Promise<ChatConversation>;
    updateChatConversation(id: number, updates: Partial<ChatConversation>): Promise<ChatConversation>;
    deleteChatConversation(id: number): Promise<void>;
    getChatMessages(conversationId: number): Promise<ChatMessage[]>;
    createChatMessage(message: InsertChatMessage): Promise<ChatMessage>;
    updateChatMessage(id: number, updates: Partial<ChatMessage>): Promise<ChatMessage>;
    getChatMessage(id: number): Promise<ChatMessage | undefined>;
}
import { MongoStorage } from './mongodb-storage';
export declare const storage: MemStorage | MongoStorage;
