/**
 * Example Usage of CaptionEditorWithTracking Component
 * 
 * This file demonstrates various usage patterns for the CaptionEditorWithTracking component.
 * These examples show how to integrate the editor with different workflows and features.
 */

import React, { useState } from 'react';
import { CaptionEditorWithTracking, CaptionVariation } from './index';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

// ============================================================================
// Example 1: Basic Usage
// ============================================================================

export function BasicEditorExample() {
  const [caption, setCaption] = useState("Check out my latest post! 🚀");

  const handleSave = async (editedCaption: string, originalCaption: string) => {
    console.log('Saving caption...');
    console.log('Original:', originalCaption);
    console.log('Edited:', editedCaption);
    
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    setCaption(editedCaption);
    alert('Caption saved successfully!');
  };

  return (
    <div className="max-w-4xl mx-auto p-6">
      <h2 className="text-2xl font-bold mb-4">Basic Caption Editor</h2>
      <CaptionEditorWithTracking
        initialCaption={caption}
        onSave={handleSave}
        placeholder="Write your caption here..."
      />
    </div>
  );
}

// ============================================================================
// Example 2: With Initial Variation Data
// ============================================================================

export function EditorWithVariationExample() {
  const mockVariation: CaptionVariation = {
    caption: "🔥 New product alert! This is a game-changer for anyone who's tired of complicated solutions. Super simple, super effective. What do you think?",
    authenticityScore: 87,
    engagementPrediction: {
      likeRate: 0.048,
      commentRate: 0.025,
      saveRate: 0.012,
      shareRate: 0.008
    },
    styleCharacteristics: {
      type: 'balanced',
      description: 'Proven formula with unique voice',
      patterns: ['Question-based engagement', 'Emoji hook'],
      hooks: ['Product launch']
    }
  };

  const handleSave = async (editedCaption: string, originalCaption: string) => {
    console.log('Caption edited from AI-generated version');
    console.log('Changes:', {
      before: originalCaption,
      after: editedCaption,
      editDistance: Math.abs(editedCaption.length - originalCaption.length)
    });

    // Record feedback to backend
    try {
      await fetch('/api/v1/ai/record-caption-feedback', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          captionId: 'generated-caption-123',
          workspaceId: 'workspace-456',
          feedbackType: 'edited',
          editedVersion: editedCaption
        })
      });
      
      alert('Caption saved and learning updated!');
    } catch (error) {
      console.error('Failed to record feedback:', error);
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-6">
      <h2 className="text-2xl font-bold mb-4">Edit AI-Generated Caption</h2>
      <p className="text-gray-600 mb-4">
        This caption was generated by AI. Edit it to match your style, and the system will learn from your changes.
      </p>
      <CaptionEditorWithTracking
        initialCaption={mockVariation.caption}
        initialVariation={mockVariation}
        onSave={handleSave}
        workspaceId="workspace-456"
        captionId="generated-caption-123"
      />
    </div>
  );
}

// ============================================================================
// Example 3: With Live Preview
// ============================================================================

export function EditorWithLivePreviewExample() {
  const [caption, setCaption] = useState("Your caption here...");
  const [livePreview, setLivePreview] = useState(caption);

  const handleCaptionChange = (newCaption: string) => {
    setLivePreview(newCaption);
  };

  const handleSave = async (editedCaption: string) => {
    setCaption(editedCaption);
    alert('Caption saved!');
  };

  return (
    <div className="max-w-6xl mx-auto p-6">
      <h2 className="text-2xl font-bold mb-4">Editor with Live Preview</h2>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Editor */}
        <div>
          <CaptionEditorWithTracking
            initialCaption={caption}
            onChange={handleCaptionChange}
            onSave={handleSave}
          />
        </div>

        {/* Live Preview */}
        <div>
          <Card>
            <CardHeader>
              <CardTitle>Instagram Post Preview</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full" />
                  <div>
                    <p className="font-semibold">your_username</p>
                    <p className="text-xs text-gray-500">Just now</p>
                  </div>
                </div>
                
                <div className="bg-gray-300 dark:bg-gray-700 aspect-square rounded-lg mb-4 flex items-center justify-center">
                  <span className="text-gray-500">Image Preview</span>
                </div>
                
                <div className="space-y-2">
                  <p className="font-semibold">your_username</p>
                  <p className="text-sm whitespace-pre-wrap">{livePreview}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

// ============================================================================
// Example 4: Multi-Stage Workflow (Generate → Select → Edit)
// ============================================================================

export function CompleteWorkflowExample() {
  const [stage, setStage] = useState<'generate' | 'select' | 'edit'>('generate');
  const [variations, setVariations] = useState<CaptionVariation[]>([]);
  const [selectedVariation, setSelectedVariation] = useState<CaptionVariation | null>(null);
  const [finalCaption, setFinalCaption] = useState<string>('');

  const mockVariations: CaptionVariation[] = [
    {
      caption: "POV: You just discovered the easiest way to create content. No more struggling with ideas! 💡",
      authenticityScore: 89,
      engagementPrediction: { likeRate: 0.052, commentRate: 0.028, saveRate: 0.015, shareRate: 0.009 },
      styleCharacteristics: { type: 'viral', description: 'High engagement viral pattern' }
    },
    {
      caption: "Here's something I learned the hard way... Creating content doesn't have to be complicated. Let me show you what works.",
      authenticityScore: 92,
      engagementPrediction: { likeRate: 0.045, commentRate: 0.032, saveRate: 0.018, shareRate: 0.012 },
      styleCharacteristics: { type: 'authentic', description: 'Personal storytelling approach' }
    },
    {
      caption: "Quick tip for content creators: simplicity wins. Here's my go-to strategy that actually works. What's yours? 👇",
      authenticityScore: 88,
      engagementPrediction: { likeRate: 0.048, commentRate: 0.030, saveRate: 0.016, shareRate: 0.010 },
      styleCharacteristics: { type: 'balanced', description: 'Proven formula + unique voice' }
    }
  ];

  const handleGenerate = () => {
    setVariations(mockVariations);
    setStage('select');
  };

  const handleSelect = (variation: CaptionVariation) => {
    setSelectedVariation(variation);
    setStage('edit');
  };

  const handleSaveEdit = async (editedCaption: string, originalCaption: string) => {
    console.log('Final caption saved');
    console.log('Original AI:', originalCaption);
    console.log('User edited:', editedCaption);
    
    setFinalCaption(editedCaption);
    
    // Record feedback
    await fetch('/api/v1/ai/record-caption-feedback', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        feedbackType: 'edited',
        originalCaption,
        editedCaption,
        captionId: 'caption-123',
        workspaceId: 'workspace-456'
      })
    });
    
    alert('Caption saved! Voice profile will be updated.');
  };

  return (
    <div className="max-w-6xl mx-auto p-6">
      <h2 className="text-2xl font-bold mb-4">Complete Caption Generation Workflow</h2>
      
      {/* Stage Indicator */}
      <div className="mb-6">
        <div className="flex items-center gap-4">
          <div className={`flex items-center gap-2 ${stage === 'generate' ? 'text-blue-600 font-semibold' : 'text-gray-400'}`}>
            <div className={`w-8 h-8 rounded-full flex items-center justify-center ${stage === 'generate' ? 'bg-blue-600 text-white' : 'bg-gray-300'}`}>
              1
            </div>
            <span>Generate</span>
          </div>
          <div className="flex-1 h-1 bg-gray-300" />
          <div className={`flex items-center gap-2 ${stage === 'select' ? 'text-blue-600 font-semibold' : 'text-gray-400'}`}>
            <div className={`w-8 h-8 rounded-full flex items-center justify-center ${stage === 'select' ? 'bg-blue-600 text-white' : 'bg-gray-300'}`}>
              2
            </div>
            <span>Select</span>
          </div>
          <div className="flex-1 h-1 bg-gray-300" />
          <div className={`flex items-center gap-2 ${stage === 'edit' ? 'text-blue-600 font-semibold' : 'text-gray-400'}`}>
            <div className={`w-8 h-8 rounded-full flex items-center justify-center ${stage === 'edit' ? 'bg-blue-600 text-white' : 'bg-gray-300'}`}>
              3
            </div>
            <span>Edit</span>
          </div>
        </div>
      </div>

      {/* Content by Stage */}
      {stage === 'generate' && (
        <Card>
          <CardHeader>
            <CardTitle>Generate Caption Variations</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-gray-600">
              Click generate to create 3 AI-powered caption variations using your voice profile and viral patterns.
            </p>
            <Button onClick={handleGenerate} size="lg">
              Generate Captions
            </Button>
          </CardContent>
        </Card>
      )}

      {stage === 'select' && (
        <div className="space-y-4">
          <h3 className="text-xl font-semibold">Select Your Favorite Variation</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {variations.map((variation, index) => (
              <Card key={index} className="cursor-pointer hover:shadow-lg transition-shadow" onClick={() => handleSelect(variation)}>
                <CardHeader>
                  <CardTitle className="text-sm">Variation {index + 1}</CardTitle>
                  <p className="text-xs text-gray-500">{variation.styleCharacteristics.type}</p>
                </CardHeader>
                <CardContent className="space-y-2">
                  <p className="text-sm">{variation.caption.substring(0, 80)}...</p>
                  <div className="text-xs text-gray-600">
                    Authenticity: {variation.authenticityScore}/100
                  </div>
                  <Button size="sm" className="w-full">Select & Edit</Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}

      {stage === 'edit' && selectedVariation && (
        <div>
          <Button variant="outline" onClick={() => setStage('select')} className="mb-4">
            ← Back to Variations
          </Button>
          <CaptionEditorWithTracking
            initialCaption={selectedVariation.caption}
            initialVariation={selectedVariation}
            onSave={handleSaveEdit}
            workspaceId="workspace-456"
            captionId="caption-123"
          />
        </div>
      )}

      {finalCaption && (
        <Card className="mt-6 bg-green-50 border-green-200">
          <CardHeader>
            <CardTitle className="text-green-800">✓ Caption Saved!</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-green-700">{finalCaption}</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

// ============================================================================
// Example 5: Custom Character Limits
// ============================================================================

export function CustomLimitsExample() {
  const [platform, setPlatform] = useState<'instagram' | 'twitter' | 'linkedin'>('instagram');
  
  const limits = {
    instagram: 2200,
    twitter: 280,
    linkedin: 3000
  };

  const handleSave = async (editedCaption: string, originalCaption: string) => {
    console.log(`Saving ${platform} caption:`, editedCaption);
    alert(`Caption saved for ${platform}!`);
  };

  return (
    <div className="max-w-4xl mx-auto p-6">
      <h2 className="text-2xl font-bold mb-4">Platform-Specific Character Limits</h2>
      
      <Tabs value={platform} onValueChange={(v) => setPlatform(v as any)} className="mb-4">
        <TabsList>
          <TabsTrigger value="instagram">Instagram (2,200)</TabsTrigger>
          <TabsTrigger value="twitter">Twitter (280)</TabsTrigger>
          <TabsTrigger value="linkedin">LinkedIn (3,000)</TabsTrigger>
        </TabsList>
      </Tabs>

      <CaptionEditorWithTracking
        key={platform}
        initialCaption={`Caption optimized for ${platform}`}
        onSave={handleSave}
        maxLength={limits[platform]}
        placeholder={`Write your ${platform} caption...`}
      />
    </div>
  );
}

// ============================================================================
// Example 6: All Examples Showcase
// ============================================================================

export function CaptionEditorExamplesShowcase() {
  return (
    <div className="space-y-12 py-8">
      <div className="max-w-6xl mx-auto px-6">
        <h1 className="text-4xl font-bold mb-2">Caption Editor Examples</h1>
        <p className="text-gray-600 mb-8">
          Explore different ways to use the CaptionEditorWithTracking component
        </p>
      </div>

      <section>
        <BasicEditorExample />
      </section>

      <section>
        <EditorWithVariationExample />
      </section>

      <section>
        <EditorWithLivePreviewExample />
      </section>

      <section>
        <CompleteWorkflowExample />
      </section>

      <section>
        <CustomLimitsExample />
      </section>
    </div>
  );
}

export default CaptionEditorExamplesShowcase;
