/**
 * cleanup-orphan-workspaces.ts
 * ---------------------------------------------------------------------------
 * One-off maintenance script to remove ORPHANED PLACEHOLDER workspaces that
 * were auto-created by older code paths (now fixed) — e.g. "My Workspace",
 * "My VeeFore Workspace" and "{username}'s Workspace" records that were
 * fabricated on signup/onboarding with NO connected brand/social account.
 *
 * Per the workspace-meta-connection spec, a workspace must always represent
 * exactly ONE connected brand and is created only via the Meta OAuth import
 * flow. A workspace with zero connected social accounts is therefore an
 * orphan placeholder.
 *
 * SAFETY (read this before running):
 *   • DRY RUN BY DEFAULT. Nothing is deleted unless you pass --apply.
 *   • Only workspaces with ZERO connected social accounts are ever candidates.
 *   • A workspace that holds CONTENT (drafts/scheduled/published posts) is
 *     NEVER deleted unless you additionally pass --include-with-content.
 *   • By default only auto-generated PLACEHOLDER NAMES are targeted
 *     ("My Workspace", "My VeeFore Workspace", "*'s Workspace"). Pass
 *     --all-empty to target every empty workspace regardless of name (use with
 *     care — this can include workspaces a user created manually but hasn't
 *     connected a brand to yet).
 *   • After deletion, the single-default-workspace invariant is repaired for
 *     each affected user (if they still have workspaces but none is default,
 *     the oldest becomes default).
 *
 * USAGE:
 *   # Preview placeholder orphans (safe, no writes):
 *   npx tsx server/scripts/cleanup-orphan-workspaces.ts
 *
 *   # Preview EVERY empty workspace:
 *   npx tsx server/scripts/cleanup-orphan-workspaces.ts --all-empty
 *
 *   # Actually delete placeholder orphans:
 *   npx tsx server/scripts/cleanup-orphan-workspaces.ts --apply
 *
 *   # Limit to a single user (by email) while testing:
 *   npx tsx server/scripts/cleanup-orphan-workspaces.ts --email someone@example.com
 * ---------------------------------------------------------------------------
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// Load the same .env the server uses (server/.. is the project root).
dotenv.config({ path: path.join(__dirname, '../../.env') });

import { connectionManager } from '../infrastructure/mongodb-connection';
import { WorkspaceModel } from '../models/Workspace/Workspace';
import { SocialAccountModel } from '../models/Social/SocialAccount';
import { ContentModel } from '../models/Content/Content';
import { User } from '../models/User';

interface Flags {
  apply: boolean;
  allEmpty: boolean;
  includeWithContent: boolean;
  email?: string;
}

function parseFlags(argv: string[]): Flags {
  const flags: Flags = {
    apply: argv.includes('--apply'),
    allEmpty: argv.includes('--all-empty'),
    includeWithContent: argv.includes('--include-with-content'),
  };
  const emailIdx = argv.indexOf('--email');
  if (emailIdx !== -1 && argv[emailIdx + 1]) {
    flags.email = argv[emailIdx + 1].trim().toLowerCase();
  }
  return flags;
}

/** True when the name looks auto-generated by an old placeholder code path. */
function isPlaceholderName(name: string | undefined | null): boolean {
  if (!name) return true; // nameless workspace is definitely not a real brand
  const n = name.trim();
  if (n === 'My Workspace') return true;
  if (n === 'My VeeFore Workspace') return true;
  if (/'s Workspace$/i.test(n)) return true;
  return false;
}

/**
 * Build a tolerant workspaceId matcher. The app stores `workspaceId` as a
 * String on social accounts / content, but historically some records may hold
 * an ObjectId. We match BOTH so we NEVER under-count references (which would
 * risk deleting a workspace that actually has data).
 */
function workspaceIdMatchers(id: mongoose.Types.ObjectId): any[] {
  const idStr = id.toString();
  const matchers: any[] = [idStr];
  if (mongoose.Types.ObjectId.isValid(idStr)) {
    matchers.push(new mongoose.Types.ObjectId(idStr));
  }
  return matchers;
}

async function run() {
  const flags = parseFlags(process.argv.slice(2));

  console.log('─'.repeat(78));
  console.log('Orphan workspace cleanup');
  console.log('  mode                :', flags.apply ? '⚠️  APPLY (will delete)' : '🔍 DRY RUN (no writes)');
  console.log('  scope               :', flags.allEmpty ? 'ALL empty workspaces' : 'placeholder-named only');
  console.log('  content protection  :', flags.includeWithContent ? 'DISABLED (will delete even with content)' : 'ENABLED');
  if (flags.email) console.log('  restricted to user  :', flags.email);
  console.log('─'.repeat(78));

  await connectionManager.connect();
  if (mongoose.connection.readyState !== 1) {
    console.error('❌ Could not establish a MongoDB connection. Aborting (nothing was changed).');
    process.exit(1);
  }
  console.log(`Connected to database: ${mongoose.connection.db?.databaseName}\n`);

  // Optional: restrict to a single user's workspaces (by email → user _id).
  let ownerFilterIds: Set<string> | null = null;
  if (flags.email) {
    const user = await User.findOne({ email: flags.email }).lean();
    if (!user) {
      console.error(`❌ No user found with email ${flags.email}. Aborting.`);
      process.exit(1);
    }
    ownerFilterIds = new Set<string>([(user._id as any).toString()]);
    console.log(`Restricting to user ${flags.email} (id ${(user._id as any).toString()})\n`);
  }

  const workspaces = await WorkspaceModel.find({}).lean();
  console.log(`Scanning ${workspaces.length} workspace(s)...\n`);

  const toDelete: Array<{
    id: mongoose.Types.ObjectId;
    name: string;
    userId: string;
    isDefault: boolean;
    contentCount: number;
  }> = [];
  const skippedHasAccounts: number[] = [];
  let skippedWrongUser = 0;
  let skippedNamedNonPlaceholder = 0;
  let skippedHasContent = 0;

  for (const ws of workspaces) {
    const wsId = ws._id as mongoose.Types.ObjectId;
    const userIdStr = ws.userId != null ? ws.userId.toString() : '';

    if (ownerFilterIds && !ownerFilterIds.has(userIdStr)) {
      skippedWrongUser++;
      continue;
    }

    const idMatchers = workspaceIdMatchers(wsId);
    const socialCount = await SocialAccountModel.countDocuments({ workspaceId: { $in: idMatchers } });

    // A workspace with a connected brand is NEVER a candidate.
    if (socialCount > 0) {
      skippedHasAccounts.push(socialCount);
      continue;
    }

    // Empty workspace — decide whether it is in scope.
    if (!flags.allEmpty && !isPlaceholderName(ws.name)) {
      skippedNamedNonPlaceholder++;
      console.log(`  ~ keep (empty, non-placeholder name): "${ws.name}"  [${wsId}] owner=${userIdStr}`);
      continue;
    }

    const contentCount = await ContentModel.countDocuments({ workspaceId: { $in: idMatchers } });
    if (contentCount > 0 && !flags.includeWithContent) {
      skippedHasContent++;
      console.log(`  ~ keep (empty of accounts but has ${contentCount} content doc(s)): "${ws.name}"  [${wsId}] owner=${userIdStr}`);
      continue;
    }

    toDelete.push({
      id: wsId,
      name: ws.name,
      userId: userIdStr,
      isDefault: ws.isDefault === true,
      contentCount,
    });
  }

  console.log('\n' + '─'.repeat(78));
  console.log('CANDIDATES FOR DELETION');
  console.log('─'.repeat(78));
  if (toDelete.length === 0) {
    console.log('None. Nothing to do.');
  } else {
    for (const c of toDelete) {
      console.log(
        `  • "${c.name}"  [${c.id}]  owner=${c.userId}` +
        `${c.isDefault ? '  (isDefault)' : ''}` +
        `${c.contentCount > 0 ? `  (⚠️ has ${c.contentCount} content docs)` : ''}`
      );
    }
  }

  console.log('\nSummary:');
  console.log(`  total workspaces scanned       : ${workspaces.length}`);
  console.log(`  skipped — has social account   : ${skippedHasAccounts.length}`);
  if (ownerFilterIds) console.log(`  skipped — other user           : ${skippedWrongUser}`);
  if (!flags.allEmpty) console.log(`  skipped — non-placeholder name : ${skippedNamedNonPlaceholder}`);
  if (!flags.includeWithContent) console.log(`  skipped — has content          : ${skippedHasContent}`);
  console.log(`  candidates for deletion        : ${toDelete.length}`);

  if (!flags.apply) {
    console.log('\n🔍 DRY RUN complete. No changes were made.');
    console.log('   Re-run with --apply to delete the candidates listed above.');
    await mongoose.disconnect();
    process.exit(0);
  }

  if (toDelete.length === 0) {
    await mongoose.disconnect();
    process.exit(0);
  }

  // ── APPLY ──────────────────────────────────────────────────────────────────
  console.log('\n⚠️  APPLYING deletions...');
  const affectedUsers = new Set<string>();
  let deleted = 0;
  for (const c of toDelete) {
    try {
      await WorkspaceModel.deleteOne({ _id: c.id });
      if (c.userId) affectedUsers.add(c.userId);
      deleted++;
      console.log(`  ✓ deleted "${c.name}" [${c.id}]`);
    } catch (err) {
      console.error(`  ✗ FAILED to delete "${c.name}" [${c.id}]:`, (err as Error).message);
    }
  }

  // ── Repair single-default invariant for affected users ──────────────────────
  console.log('\nRepairing default-workspace invariant for affected users...');
  for (const userId of affectedUsers) {
    const remaining = await WorkspaceModel.find({ userId }).sort({ createdAt: 1 }).lean();
    if (remaining.length === 0) {
      console.log(`  • user ${userId}: 0 workspaces left (valid — will connect a brand on next login)`);
      continue;
    }
    const defaults = remaining.filter((w: any) => w.isDefault === true);
    if (defaults.length === 1) {
      continue; // already healthy
    }
    // Unset all, then set the oldest as the single default.
    await WorkspaceModel.updateMany({ userId }, { $set: { isDefault: false, updatedAt: new Date() } });
    await WorkspaceModel.updateOne({ _id: remaining[0]._id }, { $set: { isDefault: true, updatedAt: new Date() } });
    console.log(`  • user ${userId}: set "${remaining[0].name}" [${remaining[0]._id}] as default (was ${defaults.length})`);
  }

  console.log(`\n✅ Done. Deleted ${deleted}/${toDelete.length} orphan workspace(s).`);
  await mongoose.disconnect();
  process.exit(0);
}

run().catch(async (err) => {
  console.error('❌ Cleanup failed:', err);
  try { await mongoose.disconnect(); } catch { /* ignore */ }
  process.exit(1);
});
