import { Response } from 'express';
import { z } from 'zod';
import { BaseController, TypedRequest } from './BaseController';
import { contentService, workspaceService } from '../services';
import { contentRepository } from '../repositories';
import { ValidationError, ForbiddenError, NotFoundError, UnauthorizedError } from '../errors';

const ContentIdParams = z.object({
  id: z.string().min(1),
});

const CreateScheduledContentSchema = z.object({
  title: z.string().min(1).max(200),
  content: z.string().min(1).max(5000),
  platform: z.string().min(1).max(50),
  scheduledAt: z.union([z.string(), z.coerce.date()]),
  workspaceId: z.string().min(1),
  mediaUrl: z.string().url().optional().nullable(),
  hashtags: z.array(z.string()).optional().default([]),
  mentions: z.array(z.string()).optional().default([]),
});

const ListScheduledQuery = z.object({
  workspaceId: z.string().min(1),
  status: z.string().optional().default('scheduled'),
});

export class SchedulerController extends BaseController {
  createScheduledContent = this.wrapAsync(async (
    req: TypedRequest<{}, z.infer<typeof CreateScheduledContentSchema>>,
    res: Response
  ) => {
    const user = req.user;
    if (!user) {
      throw new UnauthorizedError('Authentication required');
    }
    
    const input = CreateScheduledContentSchema.parse(req.body);
    
    const scheduledTime = new Date(input.scheduledAt);
    if (scheduledTime <= new Date()) {
      throw new ValidationError('Scheduled time must be in the future');
    }

    const workspaces = await workspaceService.getWorkspacesByUserId(user.id);
    const workspace = workspaces.find((w: any) => {
      const wId = (w._id || w.id)?.toString();
      return wId === input.workspaceId.toString();
    });
    if (!workspace) {
      throw new ForbiddenError('Access denied to workspace');
    }

    const scheduledContent = await contentRepository.create({
      workspaceId: input.workspaceId,
      title: input.title,
      description: input.content,
      type: 'post',
      platform: input.platform,
      status: 'scheduled',
      scheduledAt: scheduledTime,
      contentData: {
        mediaUrl: input.mediaUrl || null,
        hashtags: input.hashtags,
        mentions: input.mentions,
        createdBy: user.id,
        autoGenerated: false
      }
    });

    console.log('[SCHEDULER] Created scheduled content:', {
      id: scheduledContent.id,
      platform: input.platform,
      scheduledAt: scheduledTime.toISOString(),
      title: input.title
    });

    this.sendSuccess(res, {
      id: scheduledContent.id,
      title: input.title,
      platform: input.platform,
      scheduledAt: scheduledTime.toISOString(),
      status: 'scheduled'
    }, 201, 'Content scheduled successfully');
  });

  listScheduledContent = this.wrapAsync(async (
    req: TypedRequest<{}, {}, z.infer<typeof ListScheduledQuery>>,
    res: Response
  ) => {
    const user = req.user;
    if (!user) {
      throw new UnauthorizedError('Authentication required');
    }
    
    const { workspaceId, status } = ListScheduledQuery.parse(req.query);

    const workspaces = await workspaceService.getWorkspacesByUserId(user.id);
    const workspace = workspaces.find((w: any) => {
      const wId = (w._id || w.id)?.toString();
      return wId === workspaceId.toString();
    });
    if (!workspace) {
      throw new ForbiddenError('Access denied to workspace');
    }

    let scheduledContent = await contentService.getScheduledContent(workspaceId);
    
    if (status && status !== 'scheduled') {
      scheduledContent = scheduledContent.filter((content: any) => content.status === status);
    }
    
    const formattedContent = scheduledContent.map((content: any) => ({
      id: content.id,
      title: content.title || 'Untitled',
      description: content.description,
      platform: content.platform,
      type: content.type,
      status: content.status,
      scheduledAt: content.scheduledAt,
      mediaUrl: content.contentData?.mediaUrl,
      createdAt: content.createdAt,
      metadata: content.contentData
    }));

    this.sendSuccess(res, {
      content: formattedContent,
      total: formattedContent.length
    });
  });

  addSampleScheduledPosts = this.wrapAsync(async (
    req: TypedRequest,
    res: Response
  ) => {
    const user = req.user;
    if (!user) {
      throw new UnauthorizedError('Authentication required');
    }
    
    const workspaces = await workspaceService.getWorkspacesByUserId(user.id);
    const workspace = workspaces.find((w: any) => w.isDefault) || workspaces[0];
    
    if (!workspace) {
      throw new NotFoundError('Workspace', 'default');
    }

    const workspaceIdStr = (workspace._id || workspace.id)?.toString();

    const samplePosts = [
      {
        title: 'Monday Morning Motivation',
        description: 'Start your week strong! Monday motivation tips for entrepreneurs #MondayMotivation #Entrepreneurship #Success',
        type: 'image',
        platform: 'instagram',
        status: 'scheduled' as const,
        scheduledAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
        workspaceId: workspaceIdStr,
        creditsUsed: 1,
        contentData: {
          mediaUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400',
          hashtags: ['#MondayMotivation', '#Entrepreneurship', '#Success'],
          autoGenerated: false
        }
      },
      {
        title: 'Tech Tuesday Tips',
        description: 'Latest tech trends and tips for growing your business #TechTuesday #Innovation #DigitalMarketing',
        type: 'video',
        platform: 'instagram',
        status: 'scheduled' as const,
        scheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
        workspaceId: workspaceIdStr,
        creditsUsed: 2,
        contentData: {
          mediaUrl: 'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4',
          hashtags: ['#TechTuesday', '#Innovation', '#DigitalMarketing'],
          autoGenerated: false
        }
      },
      {
        title: 'Wednesday Wisdom',
        description: 'Midweek wisdom for business leaders. Keep pushing forward! #WednesdayWisdom #Leadership #BusinessTips',
        type: 'image',
        platform: 'facebook',
        status: 'scheduled' as const,
        scheduledAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        workspaceId: workspaceIdStr,
        creditsUsed: 1,
        contentData: {
          mediaUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
          hashtags: ['#WednesdayWisdom', '#Leadership', '#BusinessTips'],
          autoGenerated: false
        }
      }
    ];

    const createdPosts = [];
    for (const post of samplePosts) {
      const savedPost = await contentRepository.create(post);
      createdPosts.push(savedPost);
    }

    this.sendSuccess(res, {
      message: `Created ${createdPosts.length} sample scheduled posts`,
      posts: createdPosts
    }, 201);
  });

  deleteScheduledContent = this.wrapAsync(async (
    req: TypedRequest<{ id: string }>,
    res: Response
  ) => {
    const user = req.user;
    if (!user) {
      throw new UnauthorizedError('Authentication required');
    }
    
    const { id } = ContentIdParams.parse(req.params);

    const content = await contentRepository.findById(id);
    if (!content) {
      throw new NotFoundError('Content', id);
    }

    const workspaces = await workspaceService.getWorkspacesByUserId(user.id);
    const contentWorkspaceId = content.workspaceId?.toString();
    const workspace = workspaces.find((w: any) => {
      const wId = (w._id || w.id)?.toString();
      return wId === contentWorkspaceId;
    });
    if (!workspace) {
      throw new ForbiddenError('Access denied to workspace');
    }

    await contentRepository.deleteById(id);

    console.log('[SCHEDULER] Deleted scheduled content:', {
      id: content.id,
      title: content.title,
      platform: content.platform
    });

    this.sendSuccess(res, null, 200, 'Scheduled content deleted successfully');
  });
}

export const schedulerController = new SchedulerController();
