/**
 * Veefore Analytics — Metric Registry (Phase 2).
 *
 * The dictionary of {@link MetricDefinition}s: the single source of truth for
 * every metric's ID, canonical key, name, category, type, unit, lineage, and
 * data-quality (02-metrics-dictionary.md Ch 2–19). Dashboards, reports, exports,
 * and AI all resolve metric metadata from here so naming stays consistent
 * everywhere (Ch 4).
 *
 * Note on benchmarks: the documentation defines benchmark *fields* (Ch 9) but no
 * concrete numeric ranges, so none are invented here (CODING_RULES Rule 2).
 * `benchmark` is left undefined pending a documentation update; `higherIsBetter`
 * reflects inherent metric semantics (not a fabricated value).
 */

import { METRIC_IDS } from './metric-ids'
import type { MetricDefinition } from './types'

/** Current metric spec version. */
export const METRIC_SPEC_VERSION = '1.0'

/** Partial input for {@link def}; fills common defaults. */
type MetricDraft = Omit<MetricDefinition, 'version' | 'platforms'> & {
  platforms?: MetricDefinition['platforms']
}

/** Factory applying shared defaults (all platforms, current version). */
function def(draft: MetricDraft): MetricDefinition {
  return {
    platforms: 'all',
    version: METRIC_SPEC_VERSION,
    ...draft,
  }
}

/**
 * All metric definitions keyed by canonical key. Ordered by category to mirror
 * the dictionary. Only formulas that are documented (or standard, unambiguous
 * derivations of a documented metric) are described in `formula`.
 */
export const METRIC_DEFINITIONS: Record<string, MetricDefinition> = {
  // ── Account & Audience ────────────────────────────────────────────────────
  followers_total: def({
    id: METRIC_IDS.FOLLOWERS,
    key: 'followers_total',
    name: 'Followers',
    description: 'Total audience size (latest platform value).',
    category: 'account',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'latest',
    higherIsBetter: true,
  }),
  new_followers: def({
    id: METRIC_IDS.NEW_FOLLOWERS,
    key: 'new_followers',
    name: 'New Followers',
    description: 'Followers gained within the period.',
    category: 'audience',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  lost_followers: def({
    id: METRIC_IDS.LOST_FOLLOWERS,
    key: 'lost_followers',
    name: 'Lost Followers',
    description: 'Followers lost within the period.',
    category: 'audience',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: false,
  }),
  follower_growth: def({
    id: METRIC_IDS.FOLLOWER_GROWTH,
    key: 'follower_growth',
    name: 'Follower Growth',
    description: 'Net change in followers over the period.',
    category: 'audience',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'count',
    aggregation: 'none',
    formula: 'Current Followers − Previous Followers',
    dependencies: ['followers_total'],
    higherIsBetter: true,
  }),
  net_followers: def({
    id: METRIC_IDS.NET_FOLLOWERS,
    key: 'net_followers',
    name: 'Net Followers',
    description: 'New Followers minus Lost Followers.',
    category: 'audience',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'count',
    aggregation: 'none',
    formula: 'New Followers − Lost Followers',
    dependencies: ['new_followers', 'lost_followers'],
    higherIsBetter: true,
  }),
  follower_growth_rate: def({
    id: METRIC_IDS.FOLLOWER_GROWTH_RATE,
    key: 'follower_growth_rate',
    name: 'Follower Growth Rate',
    description: 'Growth efficiency as a percentage of the prior audience.',
    category: 'audience',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: '(Net New Followers / Previous Followers) × 100',
    dependencies: ['net_followers', 'followers_total'],
    higherIsBetter: true,
  }),
  audience_churn: def({
    id: METRIC_IDS.AUDIENCE_CHURN,
    key: 'audience_churn',
    name: 'Audience Churn',
    description: 'Share of the prior audience lost within the period.',
    category: 'audience',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: '(Lost Followers / Previous Followers) × 100',
    dependencies: ['lost_followers', 'followers_total'],
    higherIsBetter: false,
  }),
  audience_retention: def({
    id: METRIC_IDS.AUDIENCE_RETENTION,
    key: 'audience_retention',
    name: 'Audience Retention',
    description: 'Share of the audience retained (100 − churn).',
    category: 'audience',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: '100 − Churn%',
    dependencies: ['audience_churn'],
    higherIsBetter: true,
  }),

  // ── Reach & Impressions ──────────────────────────────────────────────────
  reach_total: def({
    id: METRIC_IDS.REACH,
    key: 'reach_total',
    name: 'Reach',
    description: 'Unique accounts reached.',
    category: 'reach',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  reach_organic: def({
    id: METRIC_IDS.REACH_ORGANIC,
    key: 'reach_organic',
    name: 'Organic Reach',
    description: 'Reach from unpaid distribution.',
    category: 'reach',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  reach_paid: def({
    id: METRIC_IDS.REACH_PAID,
    key: 'reach_paid',
    name: 'Paid Reach',
    description: 'Reach from paid distribution.',
    category: 'reach',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  reach_efficiency: def({
    id: METRIC_IDS.REACH_EFFICIENCY,
    key: 'reach_efficiency',
    name: 'Reach Efficiency',
    description: 'Reach relative to audience size.',
    category: 'reach',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'ratio',
    aggregation: 'rate',
    formula: 'Reach / Followers',
    dependencies: ['reach_total', 'followers_total'],
    higherIsBetter: true,
  }),
  reach_velocity: def({
    id: METRIC_IDS.REACH_VELOCITY,
    key: 'reach_velocity',
    name: 'Reach Velocity',
    description: 'Reach gained per hour.',
    category: 'reach',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'per_hour',
    aggregation: 'rate',
    formula: 'Reach gained / Hours',
    dependencies: ['reach_total'],
    higherIsBetter: true,
  }),
  impressions_total: def({
    id: METRIC_IDS.IMPRESSIONS,
    key: 'impressions_total',
    name: 'Impressions',
    description: 'Total times content was displayed.',
    category: 'impression',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  average_frequency: def({
    id: METRIC_IDS.AVERAGE_FREQUENCY,
    key: 'average_frequency',
    name: 'Average Frequency',
    description: 'Average number of times each reached account saw content.',
    category: 'impression',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'ratio',
    aggregation: 'rate',
    formula: 'Impressions / Reach',
    dependencies: ['impressions_total', 'reach_total'],
    higherIsBetter: true,
  }),

  // ── Engagement ───────────────────────────────────────────────────────────
  likes: def({
    id: METRIC_IDS.LIKES,
    key: 'likes',
    name: 'Likes',
    description: 'Total likes received.',
    category: 'engagement',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  comments: def({
    id: METRIC_IDS.COMMENTS,
    key: 'comments',
    name: 'Comments',
    description: 'Total comments received.',
    category: 'engagement',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  shares: def({
    id: METRIC_IDS.SHARES,
    key: 'shares',
    name: 'Shares',
    description: 'Total shares received.',
    category: 'engagement',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  saves: def({
    id: METRIC_IDS.SAVES,
    key: 'saves',
    name: 'Saves',
    description: 'Total saves/bookmarks received.',
    category: 'engagement',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  total_engagements: def({
    id: METRIC_IDS.TOTAL_ENGAGEMENTS,
    key: 'total_engagements',
    name: 'Total Engagements',
    description: 'Sum of likes, comments, shares, and saves.',
    category: 'engagement',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'count',
    aggregation: 'sum',
    formula: 'Likes + Comments + Shares + Saves',
    dependencies: ['likes', 'comments', 'shares', 'saves'],
    higherIsBetter: true,
  }),
  engagement_rate_by_followers: def({
    id: METRIC_IDS.ENGAGEMENT_RATE_BY_FOLLOWERS,
    key: 'engagement_rate_by_followers',
    name: 'Engagement Rate (by Followers)',
    description: 'Engagements relative to audience size.',
    category: 'engagement',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: 'Engagements / Followers × 100',
    dependencies: ['total_engagements', 'followers_total'],
    higherIsBetter: true,
  }),
  engagement_rate_by_reach: def({
    id: METRIC_IDS.ENGAGEMENT_RATE_BY_REACH,
    key: 'engagement_rate_by_reach',
    name: 'Engagement Rate (by Reach)',
    description: 'Engagements relative to reach.',
    category: 'engagement',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: 'Engagements / Reach × 100',
    dependencies: ['total_engagements', 'reach_total'],
    higherIsBetter: true,
  }),
  engagement_rate_by_impressions: def({
    id: METRIC_IDS.ENGAGEMENT_RATE_BY_IMPRESSIONS,
    key: 'engagement_rate_by_impressions',
    name: 'Engagement Rate (by Impressions)',
    description: 'Engagements relative to impressions.',
    category: 'engagement',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: 'Engagements / Impressions × 100',
    dependencies: ['total_engagements', 'impressions_total'],
    higherIsBetter: true,
  }),
  share_rate: def({
    id: METRIC_IDS.SHARE_RATE,
    key: 'share_rate',
    name: 'Share Rate',
    description: 'Shares relative to reach.',
    category: 'engagement',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: 'Shares / Reach × 100',
    dependencies: ['shares', 'reach_total'],
    higherIsBetter: true,
  }),
  save_rate: def({
    id: METRIC_IDS.SAVE_RATE,
    key: 'save_rate',
    name: 'Save Rate',
    description: 'Saves relative to reach.',
    category: 'engagement',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: 'Saves / Reach × 100',
    dependencies: ['saves', 'reach_total'],
    higherIsBetter: true,
  }),
  engagement_velocity: def({
    id: METRIC_IDS.ENGAGEMENT_VELOCITY,
    key: 'engagement_velocity',
    name: 'Engagement Velocity',
    description: 'Engagements gained per hour.',
    category: 'engagement',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'per_hour',
    aggregation: 'rate',
    formula: 'Engagements gained / Hours',
    dependencies: ['total_engagements'],
    higherIsBetter: true,
  }),

  // ── Facebook-specific ────────────────────────────────────────────────────
  facebook_reactions: {
    id: METRIC_IDS.FACEBOOK_REACTIONS,
    key: 'facebook_reactions',
    name: 'Facebook Reactions',
    description: 'Total reactions (Like, Love, Haha, Wow, Sad, Angry) on Facebook posts.',
    category: 'engagement',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    platforms: ['facebook'],
    higherIsBetter: true,
    version: METRIC_SPEC_VERSION,
  },
  facebook_page_views: {
    id: METRIC_IDS.FACEBOOK_PAGE_VIEWS,
    key: 'facebook_page_views',
    name: 'Facebook Page Views',
    description: 'Total views of the Facebook Page.',
    category: 'engagement',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    platforms: ['facebook'],
    higherIsBetter: true,
    version: METRIC_SPEC_VERSION,
  },
  facebook_post_clicks: {
    id: METRIC_IDS.FACEBOOK_POST_CLICKS,
    key: 'facebook_post_clicks',
    name: 'Post Clicks',
    description: 'Total clicks on Facebook posts (confirmed valid via live API probe).',
    category: 'engagement',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    platforms: ['facebook'],
    higherIsBetter: true,
    version: METRIC_SPEC_VERSION,
  },

  // ── Profile actions ──────────────────────────────────────────────────────
  profile_visits: def({
    id: METRIC_IDS.PROFILE_VISITS,
    key: 'profile_visits',
    name: 'Profile Visits',
    description: 'Visits to the profile.',
    category: 'engagement',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  website_clicks: def({
    id: METRIC_IDS.WEBSITE_CLICKS,
    key: 'website_clicks',
    name: 'Website Clicks',
    description: 'Clicks on the profile website link.',
    category: 'engagement',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  ctr: def({
    id: METRIC_IDS.CTR,
    key: 'ctr',
    name: 'Click-Through Rate',
    description: 'Clicks relative to impressions.',
    category: 'engagement',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: 'Clicks / Impressions × 100',
    dependencies: ['website_clicks', 'impressions_total'],
    higherIsBetter: true,
  }),

  // ── Video ────────────────────────────────────────────────────────────────
  video_views: def({
    id: METRIC_IDS.VIDEO_VIEWS,
    key: 'video_views',
    name: 'Total Views',
    description: 'Total views across all posts (images, carousels, reels, videos). Uses Meta\'s unified views metric (replacement for impressions, v18+).',
    category: 'video',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  video_completions: def({
    id: METRIC_IDS.VIDEO_COMPLETIONS,
    key: 'video_completions',
    name: 'Video Completions',
    description: 'Views that reached 100% of the video.',
    category: 'video',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  completion_rate: def({
    id: METRIC_IDS.COMPLETION_RATE,
    key: 'completion_rate',
    name: 'Completion Rate',
    description: 'Share of views that completed the video.',
    category: 'video',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: 'Completed Views / Views × 100',
    dependencies: ['video_completions', 'video_views'],
    higherIsBetter: true,
  }),
  total_watch_time: def({
    id: METRIC_IDS.TOTAL_WATCH_TIME,
    key: 'total_watch_time',
    name: 'Total Watch Time',
    description: 'Total seconds watched across all views.',
    category: 'video',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'seconds',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  average_watch_time: def({
    id: METRIC_IDS.AVERAGE_WATCH_TIME,
    key: 'average_watch_time',
    name: 'Average Watch Time',
    description: 'Average seconds watched per view.',
    category: 'video',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'seconds',
    aggregation: 'average',
    formula: 'Total Watch Time / Views',
    dependencies: ['total_watch_time', 'video_views'],
    higherIsBetter: true,
  }),

  // ── Publishing ───────────────────────────────────────────────────────────
  published_posts: def({
    id: METRIC_IDS.PUBLISHED_POSTS,
    key: 'published_posts',
    name: 'Published Posts',
    description: 'Posts successfully published in the period.',
    category: 'publishing',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: true,
  }),
  failed_posts: def({
    id: METRIC_IDS.FAILED_POSTS,
    key: 'failed_posts',
    name: 'Failed Posts',
    description: 'Posts that failed to publish in the period.',
    category: 'publishing',
    type: 'raw',
    dataQuality: 'verified',
    unit: 'count',
    aggregation: 'sum',
    higherIsBetter: false,
  }),
  publishing_success_rate: def({
    id: METRIC_IDS.PUBLISHING_SUCCESS_RATE,
    key: 'publishing_success_rate',
    name: 'Publishing Success Rate',
    description: 'Share of publish attempts that succeeded.',
    category: 'publishing',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: 'Published / (Published + Failed) × 100',
    dependencies: ['published_posts', 'failed_posts'],
    higherIsBetter: true,
  }),
  publishing_failure_rate: def({
    id: METRIC_IDS.PUBLISHING_FAILURE_RATE,
    key: 'publishing_failure_rate',
    name: 'Publishing Failure Rate',
    description: 'Share of publish attempts that failed.',
    category: 'publishing',
    type: 'calculated',
    dataQuality: 'calculated',
    unit: 'percent',
    aggregation: 'rate',
    formula: 'Failed / (Published + Failed) × 100',
    dependencies: ['failed_posts', 'published_posts'],
    higherIsBetter: false,
  }),

  // ── Composite scores ─────────────────────────────────────────────────────
  // Component metrics are taken from the dictionary where documented. Concrete
  // WEIGHTS are not specified in the docs and are therefore not invented here
  // (CODING_RULES Rule 2); the engine computes these only with caller-supplied
  // weights. See composite.ts.
  virality_score: def({
    id: METRIC_IDS.VIRALITY_SCORE,
    key: 'virality_score',
    name: 'Virality Score',
    description: 'Composite 0–100 score of content virality.',
    category: 'composite',
    type: 'composite',
    dataQuality: 'calculated',
    unit: 'score',
    aggregation: 'none',
    // Components per 02-metrics-dictionary.md Ch 8.
    dependencies: ['share_rate', 'save_rate', 'reach_velocity', 'engagement_velocity'],
    higherIsBetter: true,
  }),
  audience_loyalty_score: def({
    id: METRIC_IDS.AUDIENCE_LOYALTY_SCORE,
    key: 'audience_loyalty_score',
    name: 'Audience Loyalty Score',
    description: 'Composite 0–100 score of audience loyalty.',
    category: 'composite',
    type: 'composite',
    dataQuality: 'calculated',
    unit: 'score',
    aggregation: 'none',
    // Components per 02-metrics-dictionary.md Ch 12 (partial; weights pending).
    dependencies: ['audience_retention', 'shares', 'saves'],
    higherIsBetter: true,
  }),
  reach_quality_score: def({
    id: METRIC_IDS.REACH_QUALITY_SCORE,
    key: 'reach_quality_score',
    name: 'Reach Quality Score',
    description: 'Composite 0–100 score of reach quality.',
    category: 'composite',
    type: 'composite',
    dataQuality: 'calculated',
    unit: 'score',
    aggregation: 'none',
    // Factors per 02-metrics-dictionary.md Ch 13 (weights pending).
    dependencies: ['reach_efficiency', 'engagement_rate_by_reach', 'ctr'],
    higherIsBetter: true,
  }),
  engagement_quality_score: def({
    id: METRIC_IDS.ENGAGEMENT_QUALITY_SCORE,
    key: 'engagement_quality_score',
    name: 'Engagement Quality Score',
    description:
      'Composite 0–100 score of engagement quality. Component metrics and weights are pending documentation.',
    category: 'composite',
    type: 'composite',
    dataQuality: 'calculated',
    unit: 'score',
    aggregation: 'none',
    higherIsBetter: true,
  }),
  account_health_score: def({
    id: METRIC_IDS.ACCOUNT_HEALTH_SCORE,
    key: 'account_health_score',
    name: 'Account Health Score',
    description:
      'Composite 0–100 score of account health. Component metrics and weights are pending documentation.',
    category: 'composite',
    type: 'composite',
    dataQuality: 'calculated',
    unit: 'score',
    aggregation: 'none',
    higherIsBetter: true,
  }),
}

/** All metric definitions as a flat array. */
export const ALL_METRICS: MetricDefinition[] = Object.values(METRIC_DEFINITIONS)

/** Fast lookup: metric ID → definition. */
const DEFINITIONS_BY_ID: ReadonlyMap<string, MetricDefinition> = new Map(
  ALL_METRICS.map((m) => [m.id, m])
)

/** Get a metric definition by its canonical key, or `undefined`. */
export function getMetricByKey(key: string): MetricDefinition | undefined {
  return METRIC_DEFINITIONS[key]
}

/** Get a metric definition by its permanent ID, or `undefined`. */
export function getMetricById(id: string): MetricDefinition | undefined {
  return DEFINITIONS_BY_ID.get(id)
}

/** All metric definitions in a given category. */
export function getMetricsByCategory(
  category: MetricDefinition['category']
): MetricDefinition[] {
  return ALL_METRICS.filter((m) => m.category === category)
}
